etcdctl: allow move-leader to connect to multiple endpoints with TLS …
etcd-io/etcd pull request #11775
Opened 2020-04-09 16:02 UTC by benmoss

The mustClientForCmd function is responsible for parsing environment variables and flags into configuration data. A change was made in #9382 to call Fatal if a flag is provided multiple times. This means that we cannot call the mustClientForCmd function more than once, since it will think that flags parsed the first time are now being redefined and error out.

Some people have commented about this in https://github.com/etcd-io/etcd/issues/8380 but I don't think there's an open issue for it.

2020-07-30 20:14 UTC, benmoss commented
dang where's the etcd maintainers at

2020-08-26 15:49 UTC, renan commented
Will this be moving forward? This would help with maintainaining v3.4 clusters.

2020-11-24 20:36 UTC, renan commented
Not so fast, bot! We still need a reply here.

2021-02-01 20:23 UTC, ptabor requested changes
Thank you for the fix. 

Could you, please, add a regression test. 
Probably this file is a convenient place and a template:

./tests/e2e/ctl_v3_move_leader_test.go

2021-02-02 10:13 UTC, ptabor requested changes
Could you, please, add a regression test.
Probably this file is a convenient place: 

./tests/e2e/ctl_v3_move_leader_test.go

2021-02-03 16:54 UTC, closed without merging

2021-03-08 02:58 UTC, zerodayz commented
/cc @benmoss 

We hit this problem in https://bugzilla.redhat.com/show_bug.cgi?id=1918413

Is this that this PR only needs regression tests? Are you still fine to work on it @benmoss  ?

2021-03-08 20:02 UTC, benmoss commented
I don't plan to work on this, while waiting for feedback since April 9th 2020 I think I lost my motivation for seeing this bugfix through to the end 😄

2021-03-08 22:14 UTC, zerodayz commented
@benmoss  Do you mind If I pick your PR from where you left?