Change interval to 1m for etcdHighNumberOfFailedGRPCRequests critical
etcd-io/etcd pull request #12178
Opened 2020-07-28 10:26 UTC by gotjosh

We've observed an erratic behaviour of this alert during rollouts. On
all occasions, we've noticed the alert isn't sustained for more than a few
minutes and we flag it as a false positive. Because we're using the 5m rate for 5 minutes the alert only gets to see
1 sample.

Doubling the alert duration (from 5m to 10m) but that seems unfeasible
given the criticality of this, or use the 1m rate for 5m. The latter
feels like a minimal change - and it didn't cause the alert to fire on
occasions where the current one would.

Apologies for not creating an issue first, given the minimal diff of the change I thought this would be better discussed inside of a pull request. 

current interval (5m)
![Screenshot 2020-07-28 at 11 12 17](https://user-images.githubusercontent.com/231583/88654331-22405e80-d0c5-11ea-8fc2-8049d4c1ca2b.png)

proposed interval (1m)

![Screenshot 2020-07-28 at 11 24 50](https://user-images.githubusercontent.com/231583/88654346-27051280-d0c5-11ea-850a-0a800175e361.png)

Signed-off-by: gotjosh <josue@grafana.com>

2020-08-03 12:27 UTC, gotjosh commented
Just an FYI that the CI failure seems unrelated.

2020-08-18 08:45 UTC, gotjosh commented
@xiang90 apologies for ping you directly, any chance to take a look on this? 🙏

2020-11-17 09:20 UTC, pracucci commented
_Still valid for us_

2021-02-01 20:35 UTC, ptabor commented on Documentation/etcd-mixin/mixin.libsonnet
>              'for': '5m',
Does it mean that in worst case the service might by 80% of time unhealthy and the alert will not trigger ? 

4min of failures, 1 min below threshold, 4min of failures, ... 

Shell we decrease it to 2 or 3 min ?

2021-02-01 20:37 UTC, ptabor commented
Interesting. Thank you for the contribution. 
I wonder [a little off topic], what are the errors (grpc_code & method) and in what circumstances do they happen ? 
Is it a multi-node cluster being upgraded one-by-one ? 
I want to make sure there is no bug that we would be hiding by such alerting change.

2021-02-10 11:20 UTC, ptabor requested changes

2021-02-10 11:20 UTC, ptabor commented on Documentation/etcd-mixin/mixin.libsonnet
>              'for': '5m',
[marking as a requested change]

2021-02-10 21:43 UTC, spzala commented
@gotjosh thanks for the PR, and fyi that the project Doc is moved to https://github.com/etcd-io/website/ so this PR should be closed and need to open it in the doc repo. /cc @ptabor @nate-double-u

2021-02-10 21:45 UTC, spzala requested changes
@gotjosh thanks for the PR, and fyi that the project Doc is moved to https://github.com/etcd-io/website/ so this PR should be closed and need to open it in the doc repo.

2021-06-03 18:14 UTC, closed without merging