testing/e2e,grpcproxy: Fix: go test --tags "cluster_proxy" -v ./tests/e2e/...
etcd-io/etcd pull request #12273
Opened 2020-09-07 11:02 UTC by ptabor

This PR contains a bunch of fixes that makes the e2e tests work through grpc proxy: 

In particular: 
  - Connection between proxy and etcd-server is using a proper CN-less certificate. 
  - Spawned etcd-proxy service expects proper line: return v2p.waitReady("httpproxy: endpoints found")

Among others addresses request: 
  https://github.com/etcd-io/etcd/issues/11970
Is also preconditions to make sure modularization (https://github.com/etcd-io/etcd/pull/12204) is not introducing any regressions and all the tests pass (even if they didn't prior to the refactoring).
  
Tested with: 
  go test --tags "cluster_proxy" -v ./tests/e2e/...

2020-09-07 11:12 UTC, ptabor commented
@mitake @jingyih @jpbetz - please take a look.

2020-09-08 18:11 UTC, jpbetz commented
@wenjiaswe Would you be willing to look at the certs related changes?

2020-09-09 15:28 UTC, jpbetz requested changes
One very minor question about a comment then LGTM

2020-09-09 15:28 UTC, jpbetz requested changes

2020-09-09 15:28 UTC, jpbetz commented on tests/e2e/cluster_proxy_test.go
> +	// "caller":"httpproxy/director.go:65","msg":"endpoints found","endpoints":["http://localhost:20000"]}
Remove?

2020-09-09 18:05 UTC, ptabor commented on tests/e2e/cluster_proxy_test.go
> +	// "caller":"httpproxy/director.go:65","msg":"endpoints found","endpoints":["http://localhost:20000"]}
Done. PTAL.

2020-09-09 19:03 UTC, merged