Add `insecure-health-endpoint` flag to enable Kubernetes HTTP probes
etcd-io/etcd pull request #12370
Opened 2020-10-07 19:54 UTC by ironcladlou

Before this patch, Kubernetes users deploying etcd who configure mTLS
authentication for client and metrics endpoints are unable to leverage etcd's
`/health` endpoint for liveness or readiness probes because Kubernetes HTTP
probes don't support mTLS. Users must work around this limitation with
strategies like weak health checks using custom `exec` probes. Bypassing the
`/health` endpoint for this purpose can lead to false positive probe results and
quorum loss if a member is falsely determined to be ready during a rollout.

This patch introduces an `--insecure-health-endpoint` flag which, if specified,
enables an insecure HTTP `/health` endpoint which is functionally equivalent to
other `/health` endpoints. This enables etcd pods to specify reliable HTTP GET
probes for readiness and liveness checking.

This approach stands as an alternative to introducing a parallel TLS
configuration and listener just for the `/health` endpoint. The typical use case
is probably a non-exposed port used only by a container orchestration component
(e.g. the Kubelet).

Fixes https://github.com/etcd-io/etcd/issues/11993.

2020-10-08 20:43 UTC, ptabor commented on embed/config.go
> +	InsecureHealthEndpoint string `json:"insecure-health-endpoint"`
Please document that field

2020-10-08 20:44 UTC, ptabor requested changes
Please add an integration test for this functionality.

Implementation lgtm

2020-10-08 21:13 UTC, ironcladlou commented
@ptabor Sure. Do you mean an e2e test? If you really do mean integration, could you point me to a good place to introduce one? The integration tests don't _appear_ to work with the `Etcd` struct and exercise these paths. I might still be missing something.

If you did mean e2e, same question — any guidance on where this test would fix amongst existing tests? I couldn't find one that exercises things like the default metrics listener but I'm going to keep looking and playing around.

2020-10-09 13:48 UTC, ironcladlou commented on embed/config.go
> +	InsecureHealthEndpoint string `json:"insecure-health-endpoint"`
Done

2020-10-09 13:49 UTC, ironcladlou commented
@ptabor I added an e2e test covering the new endpoint and documented the field. Thanks for the feedback!

2020-10-09 14:06 UTC, ptabor commented
@ironcladlou Thank you, looks awesome. 

LGTM - as a recommendation to etcd maintainers.

2020-10-09 15:39 UTC, ironcladlou commented
The e2e fails in CI:

```
--- FAIL: TestInsecureHealthEndpointEnabled (1.04s)
    metrics_test.go:85: Get "http://localhost:20003/health": dial tcp 127.0.0.1:20003: connect: connection refused
FAIL
FAIL	go.etcd.io/etcd/tests/v3/e2e	320.513s
FAIL
FAIL: (code:1):
  % (cd tests && env go test -timeout=30m go.etcd.io/etcd/tests/v3/e2e)

ERROR: Tests for following packages failed:
   go.etcd.io/etcd/tests/v3/e2e
FAIL: 'e2e' failed at Fri Oct  9 14:15:54 UTC 2020
make: *** [docker-test] Error 1
```

I'll have to figure that out. Works locally, so something about what I'm doing here is not portable. Perhaps an environmental idiosyncrasy with localhost. I also need to add short timeouts to the client call.

2020-10-09 16:11 UTC, ptabor commented
I think a lot of tests (but mostly integrational) are using unix://sockets for communication. 

BTW: Please name your commit: 
`embed: Add `insecure-health-endpoint` flag to enable Kubernetes HTTP probes`

to mitigate: 
```
92a8037 Add `insecure-health-endpoint` flag to enable Kubernetes HTTP probes...
Expected commit title format '<package>{", "<package>}: <description>'
Got: 92a8037 Add `insecure-health-endpoint` flag to enable Kubernetes HTTP probes
FAIL: 'commit_title' failed at Fri Oct  9 14:46:23 UTC 2020
```

2020-10-12 14:51 UTC, ironcladlou commented
I was actually able to reproduce the e2e failure natively on darwin, so I'm proceeding with debugging...

2020-10-12 19:00 UTC, ironcladlou commented
@ptabor fixed the test and the commit message.

The e2e problem was that v2 was sometimes being enabled in the test etcd server due to various tests mutating shared mutable fixtures (in this case, `configTLS`) causing non-deterministic behavior depending on the test set, order, etc.

For stability and as a matter of general good practice, I think all the tests should be audited and changed as necessary to work with _copies_ of fixtures, but that's outside the scope of this PR.

2020-10-13 20:48 UTC, ptabor commented
LGTM

Could you, please point me (or open a issue) with a link to examplar configTLS modification in tests harness ?

2020-10-13 21:38 UTC, ironcladlou commented
Here's a PR which starts to fix the test state issues: https://github.com/etcd-io/etcd/pull/12392

2020-10-22 18:25 UTC, ironcladlou commented
Somehow in all this we didn't realize that additional metrics endpoints (which would also serve health) can be specified without TLS info: https://github.com/openshift/cluster-etcd-operator/blob/e1dae76a52f2ae0aa31857c5d4249e78ad47c6e0/bindata/etcd/pod.yaml#L168

Assuming the user is okay with exposing the insecure `/metrics` endpoint in this way in addition to `/health` (which I think is true in the health check scenario) maybe there's no reason for https://github.com/etcd-io/etcd/issues/11993 or this PR after all. I'll test and report back.

2020-10-23 12:39 UTC, ironcladlou commented
Looks like https://github.com/etcd-io/etcd/pull/12370#issuecomment-714676715 was the answer all along. Thanks to everyone!

/close

2020-11-19 15:45 UTC, ironcladlou commented
I'm reopening this per https://github.com/etcd-io/etcd/issues/11993#issuecomment-730461511.

2020-11-19 15:48 UTC, ironcladlou commented
@ptabor @gyuho please see https://github.com/etcd-io/etcd/issues/11993#issuecomment-730461511 — I think we still need this, otherwise it won't be possible to expose the health endpoint over HTTP without also exposing metrics insecurely, which is a constraint for us. If the approach is still agreeable I can rebase.

2021-03-09 17:16 UTC, gyuho commented
@ironcladlou Could you rebase? We'd like this to be in our 3.5 release. /cc @ptabor

2021-09-02 03:44 UTC, closed without merging

2022-11-24 04:01 UTC, new-dream commented
@ironcladlou Could you rebase? We need this feature，thanks