put support auto lease
etcd-io/etcd pull request #12474
Opened 2020-11-15 11:29 UTC by Tyraelone

etcd server and client: PUT add a new feature about auto lease.  
Usage: put  --auto-lease --auto-lease-ttl 100 key value 
Description: create a lease with given key if there is no lease, or renew lease if it exists 
Why: I want etcd put  to support auto-renew lease and if value not changed, only renew lease to reduce write ops.           
         My etcd cluster goes down when a lot of keys been deleted due to the lease expiration and come out lots of put request. Problem: because etcd cant do lease ops in txn, so this feature can't support txn. So, I hope you guys can support this feature

2020-12-09 06:43 UTC, Tyraelone commented
@jingyih jin @spzala  any idea about this?   We really want a feature like this.

2020-12-11 03:52 UTC, CMGS commented
no one care about this PR? I think it necessary to support update lease in one txn. Good job tyarelone.

2020-12-11 04:22 UTC, tangcong requested changes
I take a brief look, there are the following suggestions
1. split commit by feature
2. add test cases
3. add trace for auto lease
4. format indentation

2020-12-11 06:18 UTC, Tyraelone commented
> I take a brief look, there are the following suggestions
> 
> 1. split commit by feature
> 2. add test cases
> 3. add trace for auto lease
> 4. format indentation

Thanks, let me fill these things

2021-01-05 07:01 UTC, Tyraelone commented
@tangcong tan
added test cases for auto lease

2021-01-17 10:04 UTC, Tyraelone commented
@jingyih @tangcong @spzala

2021-01-21 03:08 UTC, CMGS commented
no update? I'm wondering who in charge of this project? no discussion no one care no response? is it the way you guys run this project and community?

2021-01-21 09:54 UTC, tangcong commented on api/etcdserverpb/rpc.proto
> -      option (google.api.http) = {
?

2021-01-21 10:41 UTC, tangcong requested changes
@Tyraelone @CMGS sorry I have been very busy recently. I take a look this PR again and found that there are still some problems that have not been solved. please also take a look. @ptabor

2021-01-21 10:43 UTC, Tyraelone commented on api/etcdserverpb/rpc.proto
> +  int64 ttl = 8;
ok,i will fix it @tangcong

2021-02-02 22:20 UTC, ptabor commented
@gyuho @jpbetz 
Its pretty significant change as it's affect public API surface. Such proposal IMHO should be discussed as Issue / doc first to decide about the desired semantic. I think we should go back to that phase. 

Few quick thoughts: 
   
   1. The PR promotes lease-per-object model that for high throughput cases was considered inefficient. Please see related discussion in Kubernetes:  https://github.com/kubernetes/kubernetes/pull/98257. 
       If we wanted to integrate auto-leasing future in etcd, maybe it should perform similar batching model. 
       
   2. What's the main purpose of the feature ?  
            a) More convenient API ? 
            b) Better performance thanks to less objects in the wire format ? 
            c) sth else
      If that's a)  -> the design should consider option when the code is contributed as part of client/v3 lib (or wrapper on top of the library).

2021-02-03 06:46 UTC, Tyraelone commented
> @gyuho @jpbetz
> Its pretty significant change as it's affect public API surface. Such proposal IMHO should be discussed as Issue / doc first to decide about the desired semantic. I think we should go back to that phase.
> 
> Few quick thoughts:
> 
> 1. The PR promotes lease-per-object model that for high throughput cases was considered inefficient. Please see related discussion in Kubernetes:  [kubernetes/kubernetes#98257](https://github.com/kubernetes/kubernetes/pull/98257).
>    If we wanted to integrate auto-leasing future in etcd, maybe it should perform similar batching model.
> 2. What's the main purpose of the feature ?
>    a) More convenient API ?
>    b) Better performance thanks to less objects in the wire format ?
>    c) sth else
>    If that's a)  -> the design should consider option when the code is contributed as part of client/v3 lib (or wrapper on top of the library).
Sorry for my poor English first.
1: we manage container health status with etcd. After a health check, we  only want to renew the lease if status not change to avoid more write ops.
2 a)  yes, convenient 
  b)  the main reason of this PR is that  we don't want to really do PUT ops if data not change

2021-02-07 07:40 UTC, Tyraelone commented on api/etcdserverpb/rpc.proto
> +  int64 ttl = 8;
@tangcong  the swag is auto generated, I need to push it too?

2021-02-07 08:40 UTC, Tyraelone commented on api/etcdserverpb/rpc.proto
> +  int64 ttl = 8;
@tangcong tang fixed.

2021-06-03 18:14 UTC, closed without merging