docs: update client v3's README
etcd-io/etcd pull request #12570
Opened 2020-12-19 16:06 UTC by juzhiyuan

Please read https://github.com/etcd-io/etcd/blob/master/CONTRIBUTING.md#contribution-flow.

2020-12-19 23:06 UTC, spzala reviewed
I am not sure what you are trying to do here?? Closing the PR, please reopen with more explanation if needed. Thanks!

2020-12-19 23:15 UTC, juzhiyuan commented
The original link is broken indeed

2020-12-20 02:24 UTC, spzala commented
> The original link is broken indeed

Hmm..I guess I might have it cached. Reopening it. Thanks for the quick reply!

2020-12-21 09:36 UTC, ptabor requested changes

2020-12-21 09:36 UTC, ptabor commented on client/v3/README.md
> +More code examples can be found at [GoDoc](https://godoc.org/github.com/rpcxio/etcd/clientv3).
The working path is: 

https://pkg.go.dev/go.etcd.io/etcd/client/v3

If you really want to point at examples, I would recommend a direct link to: 

https://github.com/etcd-io/etcd/tree/master/tests/integration/clientv3/examples

2020-12-21 09:45 UTC, ptabor approved these changes

2020-12-21 17:03 UTC, merged