etcdmain: added peer-server-{client,key}-file parameters for separating peer client and server certs
etcd-io/etcd pull request #12705
Opened 2021-02-20 21:35 UTC by astromechza

Due to some certificate authorities not issuing certificates with both client and server usage modes. We needed a way of providing explicit override certs for the server side.

The api is a little awkard, but aims to not break compatibility. Any alternative suggestions are welcomed.

Still need to check whether this is needed in the proxy flags separately and perhaps perform a bit more testing.

2021-02-22 18:57 UTC, ptabor requested changes
Could you, please, add a test that checks the new setup with separate peer & server certs ?

2021-02-28 13:05 UTC, ptabor approved these changes
LGTM. Thank you. 

Please fix the formatting nit:
```
'gofmt' started at Sun Feb 28 11:08:07 UTC 2021
integration/cluster.go
diff -u integration/cluster.go.orig integration/cluster.go
--- integration/cluster.go.orig	2021-02-28 11:08:11.164866774 +0000
+++ integration/cluster.go	2021-02-28 11:08:11.164866774 +0000
@@ -90,7 +90,7 @@
 	testTLSInfoWithSpecificUsage = transport.TLSInfo{
 		KeyFile:        "../fixtures/server-serverusage.key.insecure",
 		CertFile:       "../fixtures/server-serverusage.crt",
-		ClientKeyFile: "../fixtures/client-clientusage.key.insecure",
+		ClientKeyFile:  "../fixtures/client-clientusage.key.insecure",
 		ClientCertFile: "../fixtures/client-clientusage.crt",
 		TrustedCAFile:  "../fixtures/ca.crt",
 		ClientCertAuth: true,
```

2021-02-28 13:05 UTC, ptabor commented on pkg/transport/listener.go
> +		return nil, fmt.Errorf("ClientKeyFile and ClientCertFile must both be present[key: %v, cert: %v]", info.ClientKeyFile, info.ClientCertFile)
(or both absent)

2021-02-28 13:49 UTC, astromechza commented
Thanks @ptabor, sorry for the delay here, the e2e tests are a bit flakey on my machine so it took a bit to be confident in the change. Certs are working well now.

2021-02-28 14:40 UTC, astromechza commented
A further adjustment added to make it clear this works for proxy mode as well.

2021-02-28 15:35 UTC, astromechza commented
Great. all checks passing. @ptabor can you merge or do you know who else can take a look? @gyuho?

2021-03-02 08:03 UTC, merged