raft: postpone MsgReadIndex until first commit in the term
etcd-io/etcd pull request #12762
Opened 2021-03-11 16:17 UTC by wpedrak

This PR tries to address #12680. Instead of dropping requests while Leader didn't committed first log in the term, it records them and process afer commit (1).

#12680 could be also fixed by another approach: retry mechanism in the following code (2)

https://github.com/etcd-io/etcd/blob/3ead91ca3edf66112d56c453169343515bba71c3/server/etcdserver/v3_server.go#L752-L783 

While this PR is proposal for (1), I'd like to introduce PR for (2) as well. In my opinion implementing (1) alone, (2) alone and both seems reasonable and I'd love to hear what you think.

2021-03-11 16:49 UTC, hexfusion commented
/cc @xiang90

2021-03-11 17:22 UTC, ptabor approved these changes
Thank you. That looks good to me. 

Could you please update as well comment to: 
https://github.com/etcd-io/etcd/blob/b9226d03f4dd302dc0138456c87e55c0962f19d6/raft/node.go#L182-L186

It should state:
```
Note that request can be lost without notice, therefore it is user's job to ensure read index retries.
```

I think we should eventually audit all etcd calls of 'Propose' and 'ReadIndex' for retries, but 
still retries would add unnecessary latency. I think we should merge this PR as well.

2021-03-12 08:44 UTC, wpedrak commented
One thing that that might be worth considering is that in current setup there is no limit to `pendingReadIndexMessages` size, thus in situation when we are not able to commit after election and we are spammed with ReadIndex requests we would potentially run out of memory.

2021-03-17 07:55 UTC, ptabor commented
> there is no limit to `pendingReadIndexMessages` size, thus in situation when we are not able to commit after election and we are spammed with ReadIndex requests we would potentially run out of memory.

That would mean we have a `leader` that: 
 - is not committing anything, so is blocking all writes
 - is not propagating ReadIndex, so is blocking all reads
I think OOM is better for such a leader than staying in such state for a long time if it ever happens.

2021-03-17 07:58 UTC, ptabor commented
@tangcong @tbg @bdarnell - can you, please take a look from RAFT perspective ?

2021-03-17 20:05 UTC, bdarnell commented
I've never used ReadIndex so I'm not an expert here, but allowing a leader to OOM seems like a pretty bad outcome (consider a process that is running multiple instances of raft, or maintaining a lot of state in addition to raft). I'd prefer to avoid this amount of buffering in the raft object. 

We have some similar use cases in CockroachDB where we just retry if the leader isn't ready. In order to avoid waiting for the full timeout (500ms or whatever), we retry immediately when we see the leader commit the first empty entry of its term.

2021-03-17 21:23 UTC, gyuho commented
Is this something we can prevent at etcd server layer, and just expose the progress from raft? Just like we do for "error too many requests"? And let etcd handle the retry? Agree with @bdarnell and we should never OOM etcd server.

2021-03-17 21:40 UTC, ptabor commented
I was not precise. I don't think that the change in reality is growing the probability of OOM. 
In particular RAFT state is already 'queuing' the readOnlyIndex requests in its internal structures:

https://github.com/etcd-io/etcd/blob/63c51709b47043946bf2742a64338c7c6203e158/raft/read_only.go#L42

https://github.com/etcd-io/etcd/blob/63c51709b47043946bf2742a64338c7c6203e158/raft/read_only.go#L62

and the size of the queue is unbound. 

As long as the leader is operating and being able to breadcast messages, the queue keeps being truncated. 
The first commit by a new leader should not be different. 

BTW: Interesting idea with resending all ReadIndex on leadership change as well (although adding more 'internal dependencies' on etcd side).

2021-03-22 09:27 UTC, wpedrak commented
>  I don't think that the change in reality is growing the probability of OOM.

Indeed. If we trace execution of ReadIndex we would find out that all messages that are appended to `pendingReadIndexMessages` (slice introduced in this PR) will eventually be appended to `readIndexQueue` mentioned above. In case leader already committed entry in its turn, all those messages would go to `readIndexQueue` directly.

> BTW: Interesting idea with resending all ReadIndex on leadership change as well (although adding more 'internal dependencies' on etcd side).

@ptabor I believe that you meant retry on "first commit in current turn", not "leadership change" as we currently retry on leadership change in 
https://github.com/etcd-io/etcd/blob/3ead91ca3edf66112d56c453169343515bba71c3/server/etcdserver/v3_server.go#L717-L718

and

https://github.com/etcd-io/etcd/blob/3ead91ca3edf66112d56c453169343515bba71c3/server/etcdserver/v3_server.go#L770-L774

2021-03-22 10:10 UTC, ptabor commented
> > BTW: Interesting idea with resending all ReadIndex on leadership change as well (although adding more 'internal dependencies' on etcd side).
> 
> @ptabor I believe that you meant retry on "first commit in current turn", not "leadership change" as we currently retry on leadership change in

Correct. So potentially the trigger could go from: 
https://github.com/etcd-io/etcd/blob/8469108548abdba00b789a1b0675f357bc6503ed/server/etcdserver/server.go#L2069-L2074

2021-03-22 15:54 UTC, wpedrak commented
Makes sense. I definitely like the idea of being proactive here, however I see this as separate PR as it wouldn't share any code with proposition here.

@bdarnell @gyuho Could you elaborate on your concerns after @ptabor  and @wpedrak comments?

2021-03-22 19:57 UTC, bdarnell commented
If it's already going into a queue I'm not as worried. A second queue feels inelegant but I'm not sure how to restructure it so LGTM.

2021-03-22 22:15 UTC, gyuho requested changes
```
// Reject read only request when this leader has not committed any log entry at its term
```

I assume this time window in practice is pretty small. So, LGTM. /cc @xiang90 

Requesting some clarification and docs. Otherwise LGTM.

2021-03-22 22:15 UTC, gyuho commented on raft/raft.go
> +func reliefReadIndexMessages(r *raft) {
`releasePendingReadIndexMessages`?

2021-03-22 22:15 UTC, gyuho commented on raft/raft.go
> +func reliefReadIndexMessages(r *raft) {
Can we also add some comment?

```
// committed index has progressed for the term
// safe to respond to pending read index requests
```

2021-03-22 22:16 UTC, gyuho commented on raft/raft.go
> +					reliefReadIndexMessages(r)
```
// committed index has progressed for the term
// safe to respond to pending read index requests
reliefReadIndexMessages(r)
```

2021-03-23 13:24 UTC, wpedrak commented on raft/raft.go
> +	r.pendingReadIndexMessages = nil
I've moved this cleanup before sending messages to make sure pending messages are not handled more than once.

2021-03-23 14:57 UTC, ptabor commented
Thank you for the change. It's a big step towards seamless leadership change.

2021-03-23 14:57 UTC, merged