etcdserver: fix incorrect metrics generated when clients cancel watches
etcd-io/etcd pull request #12803
Opened 2021-03-26 17:57 UTC by cwedgwood

Manual cherry-pick of 9571325fe85173a60c89d6ac6ce3491c7b1ec7a4 for
release-3.4.

2021-03-26 20:52 UTC, cwedgwood commented
@ironcladlou @gyuho fyi & any thoughts or changes needed?

Travis' seems ok for 1 CPU and 4 so I think the 2 CPU failure is a glitch?

2021-03-29 18:04 UTC, gyuho commented
Could you update our CHANGELOG as well (can be a separate PR)

2021-03-29 18:08 UTC, cwedgwood commented
@gyuho I can but it looks like there is no applicable `CHANGELOG` in this branch?  If there is please LMK which specifically and I will make another PR.

2021-03-29 18:39 UTC, cwedgwood commented
@gyuho https://github.com/etcd-io/etcd/pull/12817 perhaps suffices?

2021-03-30 10:56 UTC, ptabor approved these changes

2021-03-31 18:40 UTC, cwedgwood commented
@ptabor @gyuho ping?
The other PS which updated the CHANGELOG merged but this is Approved but not merged yet.  That leaves things inconsistent.

2021-03-31 21:34 UTC, hexfusion requested changes
@cwedgwood please drop https://github.com/etcd-io/etcd/pull/12803/commits/c499d9b047e6c5ac2e9527981b1b12e033561c36 integration: relax leader timeout from 3s to 4s … and we can get this merged if you want to backport that change please do so with a subsequent PR. Thanks!

2021-04-01 06:35 UTC, cwedgwood commented
> @cwedgwood please drop [c499d9b](https://github.com/etcd-io/etcd/commit/c499d9b047e6c5ac2e9527981b1b12e033561c36) integration: relax leader timeout from 3s to 4s … and we can get this merged if you want to backport that change please do so with a subsequent PR. Thanks!

@hexfusion ; That change already merged.  I rebased without it all the same.  PTAL.

2021-04-01 12:17 UTC, hexfusion approved these changes
LGTM thanks @cwedgwood !

2021-04-01 12:17 UTC, merged

2021-04-01 13:27 UTC, hexfusion commented
> @hexfusion ; That change already merged. I rebased without it all the same. PTAL.

I see, missed that..