*: Remove travis
etcd-io/etcd pull request #13157
Opened 2021-06-29 09:08 UTC by serathius

Travis CI is broken for some time and was already removed from 3.4
branch.

2021-06-29 09:16 UTC, ptabor commented on .travis.yml
> -    - TARGET=linux-amd64-coverage
Can we migrate coverage ?
Was it blocked on 30min timeout ?

2021-07-01 08:52 UTC, ptabor requested changes
We need to recover the coverage tests (or at least have a bug tracing this).

2021-07-01 16:13 UTC, hexfusion commented
I think this breaks release tooling as well as a reminder

2022-01-26 10:53 UTC, serathius commented
I think we can revisit this PR as Travis is no longer enabled on Etcd repository.

2022-01-26 10:53 UTC, serathius commented
cc @spzala @ptabor @ahrtr

2022-01-28 18:39 UTC, merged