netutil:  in urlsEqual function, URL compare using individual URL fields
etcd-io/etcd pull request #13267
Opened 2021-08-03 11:00 UTC by bs-santhosh

netutil:  as part of urlsEqual function, to avoid string compare failure
of URL/IP address due to additional leading zero or different IP format,
code has been updated to compare URL fields individually.

Merge pull request #13266
Fix https://github.com/etcd-io/etcd/issues/13266

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

2021-08-09 03:57 UTC, bs-santhosh commented
while comparing urlsEqual, compare corresponding fields like IP, port and schema instead of reflect.DeepEqual on the URL's

2021-09-25 15:41 UTC, ptabor commented on pkg/netutil/netutil.go
> +		ipa:= net.ParseIP(a[i].Hostname())
What if hostname is a DNS name and not an IP ?

2021-09-25 15:41 UTC, ptabor commented on pkg/netutil/netutil.go
>  			return false, fmt.Errorf("%q(resolved from %q) != %q(resolved from %q)",
Seems we are missing comparison of the "Query" part of the URL

2021-09-25 15:42 UTC, ptabor requested changes
Please add tests showing which cases are failing with the DeepEqual implementation.

2021-09-25 16:11 UTC, ptabor commented on pkg/netutil/netutil.go
> +		ipa:= net.ParseIP(a[i].Hostname())
Oh... I see the 'resolv' above... but then... what would be the source of corruption for the comparison ?

2021-10-11 10:59 UTC, bs-santhosh commented
Using DeepEqual, below scenario used to fails, 

while starting the etcd application, if we had used FQDN/URL for  creating cluster, and we have adventise peer URLS=http://[fd74:ca9b:3a09:868c:0172:0018:0000:0035]:50041  (expanded IPv6 format - with all zero's),  etcd application would report fatal error as below, 


{"level":"fatal","ts":"2021-07-28T20:23:39.508+0900","caller":"etcdmain/etcd.go:271","msg":"discovery failed","error":"--initial-cluster has asetcd_0=http://cucpapp-555-cp1-nrcpetcd-01.t001-u000003.svc.cluster.local:50042 but missing from --initial-advertise-peer-urls=http://[fd74:ca9b:3a09:868c:0172:0018:0000:0035]:50042 (\"http://[fd74:ca9b:3a09:868c:0172:0018:0000:0035]:50042\"(resolved from \"http://[fd74:ca9b:3a09:868c:0172:0018:0000:0035]:50042\") != \"http://[fd74:ca9b:3a09:868c:172:18:0:35]:50042\"(resolved from \"http://cucpapp-555-cp1-nrcpetcd-01.t001-u000003.svc.cluster.local:50042\"))","stacktrace":"go.etcd.io/etcd/etcdmain.startEtcdOrProxyV2\n\t/tmp/etcd-release-3.4.15/etcd/release/etcd/etcdmain/etcd.go:271\ngo.etcd.io/etcd/etcdmain.Main\n\t/tmp/etcd-release-3.4.15/etcd/release/etcd/etcdmain/main.go:46\nmain.main\n\t/tmp/etcd-release-3.4.15/etcd/release/etcd/main.go:28\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:200"}

This was because of non-zero in the ip address which was returned as part of DNS i..e 
http://[fd74:ca9b:3a09:868c:0172:0018:0000:0035]:50042\") != \"http://[fd74:ca9b:3a09:868c:172:18:0:35]:50042


I have even attached etcd log  for more info.
[etcd.log](https://github.com/etcd-io/etcd/files/7321872/etcd.log)

2022-01-31 06:35 UTC, closed without merging