Add a new flag "--rev" to make-mirror command to support incremental mirror
etcd-io/etcd pull request #13519
Opened 2021-12-07 03:04 UTC by ahrtr

The current behavior of `etcdctl make-mirror ...` command is to try to copy the whole key space each time on startup. If the process/command is restarted for whatever reason, then it will take a long long time to re-sync all the data if the key space is huge. 

This PR is to add a "--rev" flag to the make-mirror command to support incrementally mirroring the data. Once the flag is provided, then the command just starts watching the key spaces starting from the specified rev. 

The PR can be a solution to the issue something like [issues/13511](https://github.com/etcd-io/etcd/issues/13511). 

@ptabor @xiang90 @sinsharat

2021-12-21 10:09 UTC, ptabor requested changes
LGTM overall.

But please add a test for the new functionality and add it to the changelog.

2021-12-22 09:01 UTC, ahrtr commented
> LGTM overall.
> 
> But please add a test for the new functionality and add it to the changelog.

@ptabor Thanks for the comment. Resolved all your comments. PTAL.

2022-01-15 16:02 UTC, ptabor approved these changes

2022-01-15 16:02 UTC, merged

2022-10-04 14:28 UTC, vukdavid commented
Is this feature available in the latest [v3.5.5](https://github.com/etcd-io/etcd/releases/tag/v3.5.5), because I don't see the `--rev` flag available?

2022-10-04 21:53 UTC, ahrtr commented
> Is this feature available in the latest [v3.5.5](https://github.com/etcd-io/etcd/releases/tag/v3.5.5)? Because I don't see the `--rev` flag available.

Usually we only backport bug fixes, so this PR isn't backported to previous stable releases, includeing 3.5 and 3.4

2022-10-06 12:57 UTC, carlosfrancia commented
@ahrtr any idea when there will be a new release containing this?

2022-10-06 20:57 UTC, ahrtr commented
> @ahrtr any idea when there will be a new release containing this?

This feature will only be included in 3.6.0. The exact release date of 3.6.0 isn't clear yet. 

If other maintainers agree to backport this PR to 3.5 (and probably 3.4), I will not object although it is a feature instead of bug fix. cc @spzala @serathius @ptabor @mitake

2023-04-03 05:55 UTC, LeeWhite187 commented
I am as well, looking for a "native" method of pushing cluster changes to a secondary cluster.
Is the incremental mirror functionality on the roadmap?

Because the make-mirror functionality doesn't appear stable in my use cases.
So, I've implemented a watcher service that packages changes, and plays them to another cluster.
Bit hokey, but works.