Use Distroless as base image
etcd-io/etcd pull request #13556
Opened 2021-12-23 13:26 UTC by yank1

Use Distroless as base image to reduce attack surface and image size.

Metioned by #13459 , #10804 and #10805 .

Signed-off-by: yankay <kay.yan@daocloud.io>

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

2021-12-24 11:25 UTC, serathius approved these changes
I haven't followed previous discussions about Etcd base image, however I'm fully supporting for switching to distroless image for security reasons.

2022-01-12 09:51 UTC, ptabor requested changes
SGTM.

Could you please add it to changelog, as it might be important that some debugging tools will not be available within the image.

2022-01-18 12:27 UTC, yank1 commented
Thanks for comments, the message have been add to changelog

> SGTM.
> 
> Could you please add it to changelog, as it might be important that some debugging tools will not be available within the image.

2022-01-21 18:42 UTC, ptabor approved these changes
Thank you. Will merge when tests are green.

2022-01-22 15:03 UTC, merged

2022-08-24 18:36 UTC, joestringer commented
Hi @yank1 , I see that this changed the base image to `gcr.io/distroless/base-debian11`. However, it seems like etcd is compiled statically so it may be possible to further reduce the attack surface by switching to `gcr.io/distroless/static-debian11`. Did you consider this option?

2022-12-21 14:44 UTC, serathius commented
It struck me when reading https://github.com/etcd-io/etcd/pull/14792. Busybox is a GPL licensed https://hub.docker.com/_/busybox https://www.busybox.net/license.html 

Not a expert, but I think there is a risk of etcd breaking busybox license by distributing docker image that busybox. My  recommendation would be to remove it. 

Problem is that we backported this PR and released v3.4.23. I would recommend to remove/replace docker images.
cc @ahrtr @ptabor @spzala.

2022-12-21 16:04 UTC, ptabor commented
Thank you Marek, for spotting this. 

My thoughts are following: 
  1. I think it didn't introduced any regression. Full debian (k8s.gcr.io/build-image/debian-base:bullseye-v1.1.0) contained also e.g. bash, that is GPL licensed software: https://www.gnu.org/licenses/gpl-3.0.html
  2. Thus I wouldn't perform any replacement in 3.4.23.
  3. Having said that, I think we might not need the busybox at all: 
        - Creation of directory can be executed using: https://docs.docker.com/engine/reference/builder/#workdir
        - I'm not sure whether we need shell technically... I don't see reason. I think it's just convenient for debugging dockers.

2022-12-22 01:03 UTC, ahrtr commented
> It struck me when reading #14792.

I assume you were talking about https://github.com/etcd-io/etcd/pull/15017 or https://github.com/etcd-io/etcd/pull/15016




> Not a expert, but I think there is a risk of etcd breaking busybox license by distributing docker image that busybox

Shouldn't it be OK as long as etcd's an open source project? 



> 3\. Having said that, I think we might not need the busybox at all:

The only impact would be that users can't log into a running container firstly and then execute command (e.g `etcdctl`). Instead, they can do it in just one command.

2023-01-20 20:48 UTC, iavael commented
@serathius if etcd doesn't link to busybox, then it's fine

2023-01-20 22:37 UTC, ahrtr commented
FYI. https://github.com/etcd-io/etcd/pull/15037