server: fix nil-pointer in applierV3backend Range
etcd-io/etcd pull request #13602
Opened 2022-01-15 15:08 UTC by AdamKorcz

`sort.Sort()` will throw a nil-dereference if its argument is `nil`. The nil-dereference will be triggered here: 
https://github.com/golang/go/blob/master/src/sort/sort.go#L230.

This PR adds a check to avoid a nil-deref for etcd users.

OSS-fuzz report: https://oss-fuzz.com/testcase-detail/4666686108729344

2022-01-15 15:45 UTC, ptabor requested changes
Thank you for the fix.

2022-01-15 15:45 UTC, ptabor commented on server/etcdserver/apply.go
> +			return nil, fmt.Errorf("sorter was nil")
Please add the error to error.go file. 
I think that the error should point on "SortTarget" field, e.g. "etcdserver: badrequest: SortTarget not supported"

2022-01-16 04:05 UTC, spzala reviewed
+1 to Piotr's comment. lgtm otherwise. Thanks @AdamKorcz

2022-01-17 10:24 UTC, serathius approved these changes
Question, for all request validation fixes in apply, should we consider having same validation to happen in API?

2022-01-17 15:47 UTC, ptabor commented
> Question, for all request validation fixes in apply, should we consider having same validation to happen in API?

Agree it would be better to perform the (state-independent) validation in: [server/etcdserver/v3_server.go](https://github.com/etcd-io/etcd/blob/22f142a9f5c39b47e5116813a7f582a488fc8aab/server/etcdserver/v3_server.go#L94): 
  it allows to refuse the request before queuing it for linearizeable read. 
  It seems it was not a practice so far, but it's never too late to start the good practices.

2022-01-17 16:07 UTC, serathius commented
> > Question, for all request validation fixes in apply, should we consider having same validation to happen in API?
> 
> Agree it would be better to perform the (state-independent) validation in: [server/etcdserver/v3_server.go](https://github.com/etcd-io/etcd/blob/22f142a9f5c39b47e5116813a7f582a488fc8aab/server/etcdserver/v3_server.go#L94): it allows to refuse the request before queuing it for linearizeable read. It seems it was not a practice so far, but it's never too late to start the good practices.

That makes me think that we should look into fuzzing validation to ensure consistency.

2022-02-06 22:07 UTC, ahrtr commented
This issue should have already been fixed in PR [pull/13555](https://github.com/etcd-io/etcd/pull/13555). So I think we can close this PR.

2022-02-07 10:23 UTC, AdamKorcz commented
> This issue should have already been fixed in PR [pull/13555](https://github.com/etcd-io/etcd/pull/13555). So I think we can close this PR.

That is correct, thanks! Closing here.

2022-02-07 10:23 UTC, closed without merging