Add bug report issue template
etcd-io/etcd pull request #13638
Opened 2022-01-24 13:41 UTC by serathius

Part of https://github.com/etcd-io/etcd/issues/13611

cc @ptabor @spzala @ahrtr

2022-01-25 08:24 UTC, ptabor approved these changes
Nice. I like it. 

Just a forward looking though: 
  Maybe we should have `etcdutl diagnose` command that collects some set of debug information automatically: 
     - layout of the files in the datadir
     - revisions/commit numbers
     - topology as seen by the masters.

2022-01-25 09:07 UTC, serathius commented
> Nice. I like it.
> 
> Just a forward looking though: Maybe we should have `etcdutl diagnose` command that collects some set of debug information automatically: - layout of the files in the datadir - revisions/commit numbers - topology as seen by the masters.

Sounds good, the more responsibility we take from users the more information we can request. Of course the tool would need to confirm with user what information it collects and that there should not be any sensitive data included.

2022-01-27 20:02 UTC, ahrtr commented
Looks great.  Before the utility `etcdutl diagnose ` is available, it will be very helpful if the user can provide output of the following two commands. Can we get it included in the template? Of course, users can obfuscate the IP address or FQDN in the output.

```
etcdctl member list -w table
etcdctl --endpoints=<member list> endpoint status -w table
```

2022-01-27 21:21 UTC, spzala requested changes
@serathius this is great. Thanks! 
One comment - there is a https://github.com/etcd-io/etcd/blob/main/.github/ISSUE_TEMPLATE.md 
I think that should be removed under this PR ?
Putting it on hold not accidentally merge it. Thanks!

2022-01-28 10:21 UTC, serathius commented
> @serathius this is great. Thanks! One comment - there is a https://github.com/etcd-io/etcd/blob/main/.github/ISSUE_TEMPLATE.md I think that should be removed under this PR ? Putting it on hold not accidentally merge it. Thanks!

I will remove it as it contents relates only to bug reports.

\
> Looks great. Before the utility `etcdutl diagnose ` is available, it will be very helpful if the user can provide output of the following two commands. Can we get it included in the template? Of course, users can obfuscate the IP address or FQDN in the output.
> 
> ```
> etcdctl member list -w table
> etcdctl --endpoints=<member list> endpoint status -w table
> ```

Sure

2022-01-28 13:47 UTC, ptabor approved these changes

2022-01-28 15:53 UTC, spzala approved these changes

2022-01-28 15:54 UTC, merged