Update go to 1.17.8
etcd-io/etcd pull request #13831
Opened 2022-03-21 23:01 UTC by mrueg

This change switches to latest go 1.17 to build etcd.

2022-03-22 09:41 UTC, serathius requested changes
Any important fixes in this release?

Please update go-version using in testing. In `.github/workflows` in `.yaml` files there is a key `go-version` used. Please update them too.

2022-03-22 10:19 UTC, mrueg commented
Good catch, missed those. 

As per https://groups.google.com/g/golang-announce/c/RP1hfrBYVuk/m/I7ouYouLAAAJ there was an issue in regexp.Compile, not sure if etcd is affected by it https://nvd.nist.gov/vuln/detail/CVE-2022-24921

2022-03-23 11:40 UTC, serathius approved these changes

2022-03-23 22:41 UTC, ahrtr approved these changes
LGTM

2022-03-24 01:56 UTC, spzala reviewed
@mrueg thank you! We should update the Changelog to reflect the version update. Can you please add a section for `Go` similar to https://github.com/etcd-io/etcd/blob/main/CHANGELOG/CHANGELOG-3.5.md#go with a single bullet `Compile with [Go 1.17+](https://golang.org/doc/devel/release.html#go1.17)`. Seems like it was missed earlier.

2022-03-24 08:58 UTC, mrueg commented
> Compile with [Go 1.17+](https://golang.org/doc/devel/release.html#go1.17)

I've added it to CHANGELOG-3.**6** as 3.5 is branched already and built with go 1.16.

2022-03-24 20:21 UTC, spzala commented
> > Compile with [Go 1.17+](https://golang.org/doc/devel/release.html#go1.17)
> 
> I've added it to CHANGELOG-3.**6** as 3.5 is branched already and built with go 1.16.

@mrueg Yup, it was for 3.6. I provided 3.5 link to use reference for the Go section. Thanks!

2022-03-24 20:21 UTC, spzala approved these changes

2022-03-24 20:23 UTC, spzala commented
All tests pass except the known semaphore issue which is unrelated.

2022-03-24 20:23 UTC, merged