tests: Add SIGKILL functional test
etcd-io/etcd pull request #13924
Opened 2022-04-11 15:52 UTC by serathius

Splitting https://github.com/etcd-io/etcd/pull/13838 into mergable code
cc @ptabor @ahrtr

2022-04-12 09:00 UTC, serathius commented
@ahrtr @ptabor PTAL

2022-04-13 02:53 UTC, ahrtr commented on tests/functional/functional.yaml
> +  - SIGKILL_FOLLOWER
`SIGKILL_ONE_FOLLOWER` so as to keep the naming consistent as the existing `SIGTERM_ONE_FOLLOWER` and `SIGQUIT_AND_REMOVE_ONE_FOLLOWER` ?

2022-04-13 02:53 UTC, ahrtr commented on tests/functional/rpcpb/rpc.proto
> +  SIGKILL_FOLLOWER = 15;
SIGKILL_ONE_FOLLOWER? The same as above.

2022-04-13 02:54 UTC, ahrtr commented
Basically looks good to me with one minor comment. 

Another comment is there are some duplicate code, such as [handler.go#L555-L565](https://github.com/etcd-io/etcd/blob/3a239f7b3b02964deb4f2dd4489856e01fbb9906/tests/functional/agent/handler.go#L555-L565). We may get them wrapped into a common function or method. But of course we can address it in a separate PR. I can do it either once this one is merged.

2022-04-13 17:23 UTC, ptabor approved these changes

2022-05-05 08:44 UTC, ptabor requested changes
nits, but marking as requiring changing for attention.

2023-01-16 09:47 UTC, closed without merging