cv3/mirror: Fetch the most recent prefix revision
etcd-io/etcd pull request #13923
Opened 2022-04-11 13:45 UTC by endocrimes

When a user sets up a Mirror with a restricted user that doesn't have
access to the `foo` path, we will fail to get the most recent revision
due to permissions issues.

With this change, when a prefix is provided we will get the initial
revision from the prefix rather than /foo. This allows restricted users
to setup sync.

Fixes  #13846

2022-04-11 13:48 UTC, endocrimes commented
@serathius I can't think of an obvious reason why this shouldn't be a reasonable approach here.

These tests should move to the common framework eventually, but I'll follow up with that seperately (as that's a larger change than is necessary to make an improvement here).

2022-04-11 13:53 UTC, serathius approved these changes
Makes sense

2022-04-11 14:12 UTC, serathius commented
cc @ptabor

2022-04-11 15:02 UTC, serathius commented
`TestMirrorSync_Authenticated`, test added in this PR, consistently fails on grpc proxy tests. Please consider fixing it or disabling the proxy case.

2022-04-11 16:12 UTC, endocrimes commented
Oh exciting - I'll take a look

2022-04-12 09:54 UTC, serathius commented
I expect that grpc proxy doesn't support the `prefix` argument correctly. If you can't find the problem I would suggest disabling this test from proxy tests (moving to separate file and adding a !proxy build flag). If we cannot fix the tests soon this will not be included in v3.5.3.

2022-04-12 12:58 UTC, ahrtr commented
lt seems the pipeline failure is caused by this PR.

2022-04-12 12:59 UTC, ahrtr requested changes
Please fix the pipeline failures.

2022-04-12 22:32 UTC, ahrtr approved these changes

2022-04-12 22:33 UTC, ahrtr commented
> Moved and disabled proxy tests for now - not sure what the issue is after a quick look and I'm heads down on jepsen testing. Will follow up with figuring out whatever is weird.

Looks good for now.

2022-04-13 09:51 UTC, merged

2022-04-13 09:52 UTC, serathius commented
@endocrimes Please send a backport to `release-3.5` if you have time.