Client: fix panics if no logger is provided to fileutil and transport.
etcd-io/etcd pull request #13947
Opened 2022-04-15 11:45 UTC by nickexported

Fixes panics in client pkg in transport that can happen if nil logger is provided. Also fixes panic with nil logger in fileutil, which is used by transport.

2022-04-16 18:54 UTC, ptabor commented
Hi Nick, 

Is there a repro using etcd client showing this problem? 
We rather assume callers responsibility to provide zap.NewNop(), rather making sure every log-line tests the logger for nullability.

2022-04-18 09:09 UTC, nickexported commented
Hi! Yes, we had a problem where we had a panic. And there is clearly a nil-logger check missing in on place. So should I just keep tests as they were? Personally, I feel like nil logger tests are overkill too, but panics aren't good either.

2022-04-19 11:38 UTC, serathius commented on client/pkg/transport/listener_test.go
> +		tlsinfo, err := SelfCert(zap.NewExample(), tmpdir, []string{"127.0.0.1"}, 1)
```suggestion
		tlsinfo, err := SelfCert(zaptest.NewLogger(t), tmpdir, []string{"127.0.0.1"}, 1)
```

2022-04-19 11:38 UTC, serathius approved these changes

2022-04-20 05:38 UTC, ahrtr commented
Thanks for the PR, which basically makes sense.  Please resolve the following two comments:
1. Please rebase this PR, and it should can resolve the pipeline failures;
2. Please organize the test cases using sub tests so as to remove the duplicate code. There are lots of good examples in the repo, such as [server_test.go#L1910-L1964](https://github.com/etcd-io/etcd/blob/52662ccd0665ee2a4991b4e99d679b67346608ac/server/etcdserver/server_test.go#L1910-L1964)

2022-04-20 05:45 UTC, ahrtr commented
After second thought, I would agree with @ptabor 's comments (copy-pasted below). We should try to keep this repo as simple/clean as possible.
1. We rather assume callers responsibility to provide zap.NewNop();
2. panic() should trigger immediate developer attention to provide proper zap.NewNop() logger.

2022-04-20 08:35 UTC, serathius commented
> After second thought, I would agree with @ptabor 's comments (copy-pasted below). We should try to keep this repo as simple/clean as possible.
> 
> 1. We rather assume callers responsibility to provide zap.NewNop();
> 2. panic() should trigger immediate developer attention to provide proper zap.NewNop() logger.

My problem with this approach is that panic will only happen occasionally when trying to report error. Caller might not even expect that function will panic as it can succeed without an error. In function `SelfCert` checking logger nil is already done in most call places, only 2 are not checking.

I think if we want to push the responsibility to set the caller to always provide the logger, panic should always happen if logger is not provided.

2022-04-20 08:43 UTC, ptabor commented
> I think if we want to push the responsibility to set the caller to always provide the logger, panic should always happen if logger is not provided.

Agree. I would be fine with either of the constructs in the first lines of the function:

```
if (lg == nil) {
  panic(fmt.Error("TouchDirAll() requires logger"));
}
```

shorter:
```
lg.Debug("Executing TouchDirAll", zap.String("dir", "dir"))  // also asserts lg != nil
```

2022-04-25 08:18 UTC, ptabor commented
> > I think if we want to push the responsibility to set the caller to always provide the logger, panic should always happen if logger is not provided.
> 
> Agree. I would be fine with either of the constructs in the first lines of the function:
> 
> 1. ```
> if (lg == nil) {
>   panic(fmt.Error("TouchDirAll() requires logger"));
> }
> ```
> 
> 2. shorter:
> 
> ```
> lg.Debug("Executing TouchDirAll", zap.String("dir", "dir"))  // also asserts lg != nil
> ```

@ahrtr @serathius Do you have opinion which of the pattern we should prefer. I would go for (2) unless the function is expected to be executed >O(100) times per second, that makes it both: performance important and very verbose.

2022-04-25 08:28 UTC, ahrtr commented
> @ahrtr @serathius Do you have opinion which of the pattern we should prefer. I would go for (2) unless the function is expected to be executed >O(100) times per second, that makes it both: performance important and very verbose.

Can we follow the similar way as what bbolt does? Example:

```
_assert(!tx.managed, "managed tx rollback not allowed")

// _assert will panic with a given formatted message if the given condition is false.
func _assert(condition bool, msg string, v ...interface{}) {
	if !condition {
		panic(fmt.Sprintf("assertion failed: "+msg, v...))
	}
}
```

FYI. [db.go#L1227](https://github.com/etcd-io/bbolt/blob/fd5535f71f488dda0915f610b6ca8c77c9ca2c59/db.go#L1227)
[tx.go#L142](https://github.com/etcd-io/bbolt/blob/fd5535f71f488dda0915f610b6ca8c77c9ca2c59/tx.go#L142)

2022-04-25 08:34 UTC, serathius commented
Like the assert approach as it is explicit. Calling debug might be removed by mistake as it doesn't imply that we are checking for logger.

2022-04-27 10:52 UTC, ahrtr commented
@nickexported Could you update this PR per [issuecomment-1108246247](https://github.com/etcd-io/etcd/pull/13947#issuecomment-1108246247) ?

2022-04-29 08:18 UTC, ptabor commented
> > @ahrtr @serathius Do you have opinion which of the pattern we should prefer. I would go for (2) unless the function is expected to be executed >O(100) times per second, that makes it both: performance important and very verbose.
> 
> Can we follow the similar way as what bbolt does? Example:
> 
> ```
> _assert(lg != nil, "nil log isn't allowed")
> 
> // _assert will panic with a given formatted message if the given condition is false.
> func _assert(condition bool, msg string, v ...interface{}) {
> 	if !condition {
> 		panic(fmt.Sprintf("assertion failed: "+msg, v...))
> 	}
> }
> ```
> 
> FYI. [db.go#L1227](https://github.com/etcd-io/bbolt/blob/fd5535f71f488dda0915f610b6ca8c77c9ca2c59/db.go#L1227) [tx.go#L142](https://github.com/etcd-io/bbolt/blob/fd5535f71f488dda0915f610b6ca8c77c9ca2c59/tx.go#L142)

SGTM.

I would consider adding verify.Assert to this package: 
  https://github.com/etcd-io/etcd/tree/main/client/pkg/verify
or introducing tiny:
  https://github.com/etcd-io/etcd/tree/main/client/pkg/assert
  
 so the code would become `verify.Assert(lg != nil, "nil log isn't allowed")`, 
 ideally Assert should support formatting: `verify.Assert(lg, "expected %v got %v", a, ,b)`

2022-04-29 08:19 UTC, ptabor requested changes
Marking as 'request changes' for the feedback from comments about adding explicit assertions for lg!=nil.

2022-04-29 08:44 UTC, ahrtr commented
@nickexported Please let me know if you need help, and I am happy to guide you to finish this PR.

2022-04-29 08:50 UTC, ahrtr commented
> I would consider adding verify.Assert to this package: https://github.com/etcd-io/etcd/tree/main/client/pkg/verify or introducing tiny: https://github.com/etcd-io/etcd/tree/main/client/pkg/assert
> 
> so the code would become `verify.Assert(lg != nil, "nil log isn't allowed")`, ideally Assert should support formatting: `verify.Assert(lg, "expected %v got %v", a, ,b)`

The only comment is probably we need to perform the assertion in production/runtime environment, which means it shouldn't depend on the verification switch on/off.

2022-04-29 12:37 UTC, nickexported commented
@ahrtr thanks, I'l make fixes as described here and come back

2022-05-13 11:45 UTC, ahrtr commented
Please use the function [verify.Assert](https://github.com/etcd-io/etcd/blob/29d30ab7b01f70375aa322fdbddb31a5acf7e003/client/pkg/verify/verify.go#L76), see also [4022#discussion_r872293596](https://github.com/etcd-io/etcd/pull/14022#discussion_r872293596)

2022-08-08 22:10 UTC, ahrtr commented
@nickexported  Please resolve review comments and conflicts.

2022-09-13 11:20 UTC, ahrtr commented
Since no response from the author for a long time, so I resolved it in https://github.com/etcd-io/etcd/pull/14455

2022-09-13 11:20 UTC, closed without merging