wal: remove the repeated test case
etcd-io/etcd pull request #14106
Opened 2022-06-13 03:36 UTC by SimFG

The TestFilePipelineFailLockFile case maybe test the line 77 in the alloc function. But the LockFile will not throw an error when the file lock is hold. And TestFilePipelineFailPreallocate and TestFilePipelineFailLockFile are exactly the same except for the comments.

2022-06-13 08:38 UTC, ptabor requested changes
Thank you for finding. Indeed this piece of code is not adding any value. 

Could you, please, lock manually the file `0.tmp` in the preamble of the test, such that: 
https://github.com/etcd-io/etcd/blob/4592af25ba3b9b9d249845d7d376fe0f7c5ba9de/server/storage/wal/file_pipeline.go#L77 would fail.

2022-06-14 08:37 UTC, ptabor approved these changes
Thank you for checking.

Optionally: Please add a comment to fp.Open(...) method that it will 'block' if the lock is already taken.

2022-06-14 09:27 UTC, SimFG commented
@ptabor I have commented in this method

2022-06-14 09:37 UTC, serathius approved these changes

2022-06-14 10:13 UTC, merged