[3.5] server: don't panic in readonly serializable txn
etcd-io/etcd pull request #14178
Opened 2022-06-29 08:04 UTC by lavacat

Problem: We pass grpc context down to applier in readonly serializable txn.
This context can be cancelled for example due to timeout.
This will trigger panic inside applyTxn

Solution: Only panic for transactions with write operations

fixes https://github.com/etcd-io/etcd/issues/14110
backported from main

Signed-off-by: Bogdan Kanivets <bkanivets@apple.com>

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

2022-08-13 21:55 UTC, ahrtr commented on server/etcdserver/apply.go
> +	if err != nil && isWrite {
```suggestion
	if err != nil {
```

2022-08-13 21:56 UTC, ahrtr commented
Please update this PR per https://github.com/etcd-io/etcd/pull/14149

2022-08-29 19:45 UTC, ptabor requested changes
Marking as requiring sync with the 'main' variant of the PR.

2022-08-30 00:25 UTC, lavacat commented
Sorry about delay. Will update soon.

2022-09-13 06:24 UTC, lavacat commented
@ahrtr @ptabor FYI, this is ready to merge

2022-09-13 06:39 UTC, ahrtr approved these changes
LGTM 

Thank you @lavacat 

Please drop a message next time when you finish all requested change.

2022-09-13 06:44 UTC, ahrtr commented
This is just a backport PR, so merging...

Please add a changelog item if you haven't done it. @lavacat

2022-09-13 06:44 UTC, merged