etcdctl: add --max-txn-ops flag
etcd-io/etcd pull request #14340
Opened 2022-08-12 08:52 UTC by xakdwch

### what is this

--max-txn-ops flag allows users to define the maximum number of operations permitted in
a transaction during syncing updates.if unlimited syncing may fail when number of txn ops
exceeds the maximum number of server side.

### why need this

DefaultMaxTxnOps in server is 128. it also can be defined by the --max-txn-ops flag in etcd server side.
if the number of operations permitted per transaction exceeds the limitation during make-mirror, 
make-mirror will crash.

> 2022/08/12 14:58:44 INFO: [core] [Channel #3 SubChannel #4] Subchannel Connectivity change to IDLE
2022/08/12 14:58:44 INFO: [balancer] base.baseBalancer: handle SubConn state change: 0xc00057c550, IDLE
2022/08/12 14:58:44 INFO: [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
2022/08/12 14:58:44 INFO: [roundrobin] roundrobinPicker: Build called with info: {map[]}
2022/08/12 14:58:44 INFO: [core] [Channel #3] Channel Connectivity change to IDLE
2022/08/12 14:58:44 INFO: [core] [Channel #3 SubChannel #4] Subchannel Connectivity change to CONNECTING
2022/08/12 14:58:44 INFO: [core] [Channel #3 SubChannel #4] Subchannel picks a new address "10.20.144.27:2379" to connect
2022/08/12 14:58:44 INFO: [balancer] base.baseBalancer: handle SubConn state change: 0xc00057c550, CONNECTING
2022/08/12 14:58:44 INFO: [core] [Channel #3] Channel Connectivity change to CONNECTING
2022/08/12 14:58:44 INFO: [core] [Channel #3 SubChannel #4] Subchannel Connectivity change to READY
2022/08/12 14:58:44 INFO: [balancer] base.baseBalancer: handle SubConn state change: 0xc00057c550, READY
2022/08/12 14:58:44 INFO: [roundrobin] roundrobinPicker: Build called with info: {map[0xc00057c550:{{
  "Addr": "10.20.144.27:2379",
  "ServerName": "10.20.144.27",
  "Attributes": null,
  "BalancerAttributes": null,
  "Type": 0,
  "Metadata": null
}}]}
2022/08/12 14:58:44 INFO: [core] [Channel #3] Channel Connectivity change to READY
17313
{"level":"warn","ts":"2022-08-12T14:59:21.543+0800","logger":"etcd-client","caller":"v3/retry_interceptor.go:64","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0001c85a0/192.168.48.220:2379","method":"/etcdserverpb.KV/Txn","attempt":0,"error":"rpc error: code = InvalidArgument desc = etcdserver: too many operations in txn request"}
Error: etcdserver: too many operations in txn request

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

2022-08-12 22:20 UTC, ahrtr commented on etcdctl/ctlv3/command/make_mirror_command.go
> +	maxTxnOps = int(128)
rename to `defaultMaxTxnOps`?

2022-08-13 05:12 UTC, xakdwch commented on etcdctl/ctlv3/command/make_mirror_command.go
> +	maxTxnOps = int(128)
yeah of course

2022-08-13 22:11 UTC, ahrtr commented on etcdctl/ctlv3/command/make_mirror_command.go
> +	defaultMaxTxnOps = int(128)
```suggestion
	defaultMaxTxnOps uint = 128
```

2022-08-13 22:11 UTC, ahrtr commented on etcdctl/ctlv3/command/make_mirror_command.go
> +	mmmaxTxnOps    int
```suggestion
	mmmaxTxnOps    uint
```

2022-08-13 22:11 UTC, ahrtr commented on etcdctl/ctlv3/command/make_mirror_command.go
> +	c.Flags().IntVar(&mmmaxTxnOps, "max-txn-ops", defaultMaxTxnOps, "Maximum number of operations permitted in a transaction during syncing updates.")
```suggestion
	c.Flags().UintVar(&mmmaxTxnOps, "max-txn-ops", defaultMaxTxnOps, "Maximum number of operations permitted in a transaction during syncing updates.")
```

2022-08-13 22:12 UTC, ahrtr commented
Overall looks good to me, but please keep it consistent with the existing flag in [etcd](https://github.com/etcd-io/etcd/blob/fff5d00ccfddaf5f06fa11cad65c1ecaa8c09f87/server/etcdmain/config.go#L133)

2022-08-14 12:33 UTC, xakdwch commented
/retest

2022-08-14 22:02 UTC, ahrtr approved these changes
LGTM

Thank you @xakdwch 

cc @spzala

2022-08-15 00:02 UTC, ahrtr commented
Please also add an item into the [changelog-3.6](https://github.com/etcd-io/etcd/blob/main/CHANGELOG/CHANGELOG-3.6.md)

2022-08-15 01:36 UTC, spzala requested changes
Thanks @xakdwch We should update README as well - https://github.com/etcd-io/etcd/blob/main/etcdctl/README.md#make-mirror-options-destination Also, as @ahrtr pointed out, please update the CHANGELOG.

2022-08-15 06:21 UTC, xakdwch commented
> Thanks @xakdwch We should update README as well - https://github.com/etcd-io/etcd/blob/main/etcdctl/README.md#make-mirror-options-destination Also, as @ahrtr pointed out, please update the CHANGELOG.



> Thanks @xakdwch We should update README as well - https://github.com/etcd-io/etcd/blob/main/etcdctl/README.md#make-mirror-options-destination Also, as @ahrtr pointed out, please update the CHANGELOG.

ack and updated

2022-08-15 06:24 UTC, xakdwch commented
> Thanks @xakdwch We should update README as well - https://github.com/etcd-io/etcd/blob/main/etcdctl/README.md#make-mirror-options-destination Also, as @ahrtr pointed out, please update the CHANGELOG.



> Thanks @xakdwch We should update README as well - https://github.com/etcd-io/etcd/blob/main/etcdctl/README.md#make-mirror-options-destination Also, as @ahrtr pointed out, please update the CHANGELOG.

ack and updated

2022-08-15 07:56 UTC, xakdwch commented
> Please also add an item into the [changelog-3.6](https://github.com/etcd-io/etcd/blob/main/CHANGELOG/CHANGELOG-3.6.md)

updated

2022-08-16 14:55 UTC, spzala approved these changes
Thanks @xakdwch 
lgtm. The build failure not related, re-running.

2022-08-16 21:36 UTC, merged