Move grpc-proxy item from 3.6 to 3.5 changelog
etcd-io/etcd pull request #14524
Opened 2022-09-26 20:04 UTC by dusk125

Since I'm backporting #14308 from 3.6 to 3.5, I need to move the changelog line to 3.5

2022-09-26 20:07 UTC, ahrtr commented on CHANGELOG/CHANGELOG-3.5.md
> +- Add [`etcd grpc-proxy start --listen-cipher-suites`](https://github.com/etcd-io/etcd/pull/14308) flag to support adding configurable cipher list.
```suggestion
- Add [`etcd grpc-proxy start --listen-cipher-suites`](https://github.com/etcd-io/etcd/pull/14500) flag to support adding configurable cipher list.
```

2022-09-26 23:59 UTC, ahrtr commented
Please also update the changelog-3.4 after you backport the fix to 3.4.

2022-10-03 19:54 UTC, spzala requested changes
@dusk125 thanks but why are removing the entry from the 3.6 changelog? I think you just need to update the 3.5 changelog. Also, I think you may not need a separate PR (this PR) for changelog as the PR https://github.com/etcd-io/etcd/pull/14500 is still open and you can modify the changelog there to keep it clean (something you did in the https://github.com/etcd-io/etcd/pull/14308). Thanks!

2022-10-03 22:42 UTC, ahrtr commented
@spzala Please refer to https://github.com/etcd-io/etcd/pull/14476#issuecomment-1249192558 to get the reason of why removing the changelog item from 3.6. Please also kindly share your thoughts. Probably we should clearly document the rules in [CHANGELOG/README.md ](https://github.com/etcd-io/etcd/blob/main/CHANGELOG/README.md ) if you agree.

2022-10-05 01:51 UTC, spzala reviewed
Please fix merge conflict. Thanks @dusk125

2022-10-05 01:55 UTC, spzala commented
> @spzala Please refer to [#14476 (comment)](https://github.com/etcd-io/etcd/pull/14476#issuecomment-1249192558) to get the reason of why removing the changelog item from 3.6. Please also kindly share your thoughts. Probably we should clearly document the rules in [CHANGELOG/README.md ](https://github.com/etcd-io/etcd/blob/main/CHANGELOG/README.md) if you agree.

@ahrtr thanks and I see, I am fine with the PR changes in that case. And, yes, we definitely should update the changelog README. I think we need some more discussions, and we can discuss it more cleanly in a PR for README update. Hope that makes sense.

2022-10-05 01:57 UTC, ahrtr commented
> > @spzala Please refer to [#14476 (comment)](https://github.com/etcd-io/etcd/pull/14476#issuecomment-1249192558) to get the reason of why removing the changelog item from 3.6. Please also kindly share your thoughts. Probably we should clearly document the rules in [CHANGELOG/README.md ](https://github.com/etcd-io/etcd/blob/main/CHANGELOG/README.md) if you agree.
> 
> @ahrtr thanks and I see, I am fine with the PR changes in that case. And, yes, we definitely should update the changelog README. I think we need some more discussions, and we can discuss it more cleanly in a PR for README update. Hope that makes sense.

Makes sense to me. Please feel free to deliver a PR for this or Please let me know if you want me to deliver a PR.

2022-10-15 21:46 UTC, spzala approved these changes

2022-10-15 22:38 UTC, ahrtr commented
Thanks both @dusk125 and @spzala 

There is a discussion recently related to the rules of adding changelog items. FYI. https://github.com/etcd-io/etcd/pull/14570#discussion_r992787725 . Based on the discussion, the main changelog gives one place to see what's changed over previous minor or major release, so we should add the changelog item for 3.6 back.

2022-10-19 23:12 UTC, ahrtr requested changes
Please add an item for 3.4 and add the item for 3.6 back.

2022-10-27 06:24 UTC, ahrtr commented
@dusk125  Please update this PR per the comment above so that we can merge it.

2022-10-27 21:03 UTC, ahrtr commented
Please rebase this PR and add the changelog item for 3.6 back (FYI. https://github.com/etcd-io/etcd/pull/14524#issuecomment-1279844792 )

2022-10-28 17:11 UTC, dusk125 commented
> Please rebase this PR and add the changelog item for 3.6 back (FYI. [#14524 (comment)](https://github.com/etcd-io/etcd/pull/14524#issuecomment-1279844792) )

This PR was the one that removed the 3.6 changelog entry; since it didn't get merged before the change was backported to 3.4, the 3.6 changelog entry is still there and hasn't been removed.

2022-10-28 21:25 UTC, ahrtr commented
> > Please rebase this PR and add the changelog item for 3.6 back (FYI. [#14524 (comment)](https://github.com/etcd-io/etcd/pull/14524#issuecomment-1279844792) )
> 
> This PR was the one that removed the 3.6 changelog entry; since it didn't get merged before the change was backported to 3.4, the 3.6 changelog entry is still there and hasn't been removed.

Thanks for the clarification.

2022-10-28 21:57 UTC, ahrtr approved these changes
LGTM

Thank you @dusk125

2022-10-28 21:57 UTC, merged