etcdutl: Add flag to ignore bootstrap verificaiton during restore
etcd-io/etcd pull request #14546
Opened 2022-10-03 12:41 UTC by pchan

Some of the bootstrap verification is not applicable during restore. The flag enables skipping these verification.
Fixes : #14456 

Signed-off-by: Prasad Chandrasekaran <pchan@github.com>

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.
Passes unit testing.

2022-10-03 23:37 UTC, ahrtr commented
Please refer to https://github.com/etcd-io/etcd/issues/14456#issuecomment-1266201279 , and also please remember to signoff commit using `git rebase HEAD~1 --signoff`

2022-10-05 14:27 UTC, ptabor commented on etcdutl/etcdutl/snapshot_command.go
> +	ignoreBootstrapVerify bool,
maybe call it `ignoreExternalVerification` to stress that we want to skip the 'not hermetic' verifications, that e.g. depends on DNS.

2022-10-05 14:34 UTC, ptabor requested changes
Please add a test that reproduces the problem to make sure we will not regress in this area.

Probably slight variant of existing snapshot/restore tests (https://github.com/etcd-io/etcd/blob/main/tests/e2e/ctl_v3_snapshot_test.go) would work.

2022-10-05 15:02 UTC, ahrtr commented
Just to be clearer, this issue has already been resolved in main branch in https://github.com/etcd-io/etcd/pull/13224, so we just need to backport the PR to 3.5 and  3.4.  FYI. https://github.com/etcd-io/etcd/issues/14456#issuecomment-1266201279

2022-10-05 15:08 UTC, pchan commented
> Please add a test that reproduces the problem to make sure we will not regress in this area.
> 
> Probably slight variant of existing snapshot/restore tests (https://github.com/etcd-io/etcd/blob/main/tests/e2e/ctl_v3_snapshot_test.go) would work.

Thanks for the feedback, as @ahrtr mentioned I will be backporting the #13224 fix to 3.5 and 3.4.

2022-10-05 15:10 UTC, pchan commented
Closing this PR as #13224 addresses the problem in main.

2022-10-05 15:10 UTC, closed without merging