docker: remove nsswitch.conf
etcd-io/etcd pull request #15155
Opened 2023-01-20 20:57 UTC by iavael

Since docker images are not alpine-based anymore and do support nss, nsswitch.conf hack is not required anymore

2023-01-20 22:50 UTC, ahrtr approved these changes
Good catch! 

Thank you @iavael 

Could you backport this PR to 3.5 and 3.4?

2023-01-21 10:00 UTC, serathius commented
Simplifying dockerfiles has been on my mind for long time. Thanks for looking into this!

2023-01-21 10:00 UTC, serathius commented
@ahrtr There is no need to backport this. This is more of a cleanup. Let's not backport cleanups.

2023-01-21 22:07 UTC, ahrtr commented
> @ahrtr There is no need to backport this. This is more of a cleanup. Let's not backport cleanups. I doesn't benefit older releases and would only confuse users reading changelog.

Actually it's a minor issue (introduced in one of my previous PRs) to me. There are two duplicate keys "hosts", see line 21 and line 12. 
https://github.com/etcd-io/etcd/blob/215b53cf3b48ee761f4c40908b3874b2e5e95e9f/nsswitch.conf#L21
https://github.com/etcd-io/etcd/blob/215b53cf3b48ee761f4c40908b3874b2e5e95e9f/nsswitch.conf#L12

I suggest to backport the PR.

2023-01-21 22:10 UTC, ahrtr commented
Since 3.4.24 isn't released yet, and so no need to update the changelog for 3.4. Note all dockerfile/nsswitch.conf changes are only included in 3.4.24.

2023-01-22 21:43 UTC, iavael commented
@ahrtr 
> Could you backport this PR to 3.5 and 3.4?

PRs created

2023-01-22 23:46 UTC, ahrtr commented
> @ahrtr
> 
> > Could you backport this PR to 3.5 and 3.4?
> 
> PRs created

Thank you @iavael .  I see that you marked both PRs as draft, anything else you want to update on them? Both of them seems good to me. Please mark them as ready for review if you think they are ready.

2023-01-22 23:50 UTC, ahrtr commented
Please also add a changelog item for 3.5 in [CHANGELOG-3.5.md](https://github.com/etcd-io/etcd/blob/main/CHANGELOG/CHANGELOG-3.5.md).

Since the PR adding `nsswitch.conf` isn't included in the latest 3.4 release (3.4.23) yet, so no need to add changelog item for 3.4.

2023-01-23 10:22 UTC, ahrtr commented on CHANGELOG/CHANGELOG-3.5.md
> +- Update [Remove nsswitch.conf from docker image](https://github.com/etcd-io/etcd/pull/15155)
```suggestion
- [Remove nsswitch.conf from docker image](https://github.com/etcd-io/etcd/pull/15155)
```

2023-01-24 00:16 UTC, ahrtr requested changes
Please rebase this PR and resolve the comment for changelog

2023-01-25 22:48 UTC, ahrtr commented on CHANGELOG/CHANGELOG-3.5.md
> +- [Remove nsswitch.conf from docker image](https://github.com/etcd-io/etcd/pull/15155)
```suggestion
- [Remove nsswitch.conf from docker image](https://github.com/etcd-io/etcd/pull/15161)
```

2023-01-25 22:49 UTC, ahrtr commented
Please squash the commits into one.

2023-02-01 07:59 UTC, ahrtr commented
@iavael please resolve the conflict and squash the commits.

2023-02-02 09:58 UTC, ahrtr commented
There is still conflict.

2023-02-02 11:29 UTC, ahrtr approved these changes
LGTM

Thanks @iavael

2023-02-02 22:37 UTC, merged