tests/framework/e2e: kill etcd cluster processes after test finished
etcd-io/etcd pull request #15637
Opened 2023-04-04 07:10 UTC by chaochn47

REF: https://github.com/etcd-io/etcd/issues/15497

Before:

It is 28.9mins which is close to 30mins timeout
```
% (cd tests && 'env' 'ETCD_VERIFY=all' 'go' 'test' 'go.etcd.io/etcd/tests/v3/common' '--tags=e2e' '-timeout=30m')
ok  	go.etcd.io/etcd/tests/v3/common	1735.430s
```
https://github.com/etcd-io/etcd/actions/runs/4602707842/jobs/8131973032?pr=15580

After:
TBD
```
```

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

2023-04-04 07:54 UTC, serathius commented
I'm not sure that we want to make force killing the default behavior for all tests. Ensuring that process exits correctly and gracefully is also important thing to test. It's not important for robustness tests, because their goal is not to test etcd binary, but the API. E2e should explicitly test etcd binary.

I would rather go into direction of finding set of tests that take too long and checking the reason. If the reason is etcd shutdown taking long then we can selectively use force kill. However I don't expect that most e2e tests have the same problem as robustness tests as by design most of them are not disruptful as robustness tests are.

2023-04-04 08:03 UTC, chaochn47 commented
@serathius sorry for the disruption and the scary PR. I was prematurely publishing the PR. 

For the detailed analysis, can you take a look at this comment in the original issue? Summary is "Test duration of test case including PeerTLS or PeerAutoTLS which has cluster size is 3 is unexpectedly too high"  https://github.com/etcd-io/etcd/issues/15497#issuecomment-1495480917

2023-04-04 10:29 UTC, serathius commented
Don't worry about publishing PR, I wanted to give my feedback early to make sure the direction is correct.

2023-04-11 05:20 UTC, chaochn47 commented
The issue analysis is posted in https://github.com/etcd-io/etcd/issues/15497#issuecomment-1496368300. 

Could you please take a look if this PR makes sense to you? It helps greatly reduce the e2e test runtime and improve each contributor dev experience. Thanks!!

@serathius @ahrtr @jmhbnz

2023-04-11 07:28 UTC, jmhbnz approved these changes
Great analysis in the linked issue @chaochn47.  

I think there is perhaps a followup pr to also make some changes to what tests use 3 node cluster versus 1 to further improve execution times. It's a good idea to keep the changes separate and do in small chunks.

Just taking the analysis in the linked issue at face value as I am still learning a lot of this code and don't have much project history yet. With that in mind then looking at these changes the code itself looks ok to me and I think it will be a good outcome if this merges however maintainers may have some more nuanced feedback.

2023-04-11 08:59 UTC, serathius approved these changes

2023-04-11 09:10 UTC, fuweid approved these changes
LGTM. Great work!

I think if the case doesn't verify the graceful shutdown, it should use force cleanup.

2023-04-11 09:23 UTC, serathius commented
Followup based on @fuweid, could you add tests for graceful shutdown in for all etcd cluster configurations? That would be the only tests that doesn't use forceful shutdown with 3 members.

2023-04-11 19:37 UTC, serathius commented
> @serathius I am not sure what's the expected graceful shutdown behavior. Could you please elaborate a little more?

Last time I looked, leader will try to pass leadership before exiting. So we should have a tests for that behavior:
* Test that in 3 member cluster leader will try to pass leadership when shut down 
* Test that in 3 member cluster leader will still shutdown if it cannot pass down leadership.
* Test that in 1 member cluster passing leader is skipped

> As the first step, I will create another PR includes the following
> 
> ```
> For a cluster configuration enumeration:
> 			clus := testRunner.NewCluster(ctx, t, config.WithClusterConfig(tc.config))
> 			defer clus.Close()
> ```
> 
> It's effectively the same as current test coverage.
> 
> And improve incrementally based on the expected graceful shutdown behavior, what do you think?

Don't understand the proposal. Can you describe the what you want to change?

2023-04-11 19:43 UTC, chaochn47 commented
> Last time I looked, leader will try to pass leadership before exiting. So we should have a tests for that behavior
Thanks!! That's very helpful.

> Don't understand the proposal. Can you describe the what you want to change?
Sorry for the confusion. 

The proposal is to creating a 3 member cluster, send SIGTERM signal to each process and wait for the etcd process graceful shutdown (transfer leadership) and exits. It's effectively the same as current test coverage in `tests/common`.

2023-04-11 19:52 UTC, serathius commented
It would be better to have some assertions in the tests instead of just testing that process can be killed. Please see my suggestions in above comments on what graceful shutdown scenarios we should test

2023-04-11 20:00 UTC, chaochn47 commented
I see. Thanks!! That is very helpful.

2023-04-12 01:15 UTC, ahrtr commented
I agree that the long delay (of stopping the last member) is caused by [TransferLeadership](https://github.com/etcd-io/etcd/blob/6519a15db4c889601b713dac575379790d7fb691/server/etcdserver/server.go#L1256). Great finding @chaochn47 . The reason is that our e2e test stops all members concurrently. When the last member tries to transfer the leadership to another member, which is also in progress of stopping, so the operation will always timeout ([7s](https://github.com/etcd-io/etcd/blob/6519a15db4c889601b713dac575379790d7fb691/server/config/config.go#L323-L325) by default). 

In production, usually users won't stop all members concurrently; instead they stop member one by one (e.g. rolling upgrade or update). So I think we should support both sequentially/synchronously and concurrently/asynchronously stopping a multi-member cluster in our e2e test, and defaults to sequentially/synchronously.  Of course, we should apply a timeout when stopping each member, but usually it should be fast enough, and we shouldn't see any performance reduce as compare to the existing concurrent stopping.

We can intentionally add a couple of cases to test concurrent stopping. 

In the meanwhile, I agree with @fuweid that we should also support cleaning up zombie process at the end of each e2e test case. It can be done separately.

2023-04-12 01:19 UTC, ahrtr requested changes
Forcibly stopping a cluster isn't a best practice, and it should be only a method of cleanup just in case. 

Please try to follow https://github.com/etcd-io/etcd/pull/15637#issuecomment-1504376401  to stop cluster members sequentially. 

Suggested plan/steps:
1. stop cluster members sequentially.
2. add test cases to test concurrent stopping;
3. support cleaning up zombie process at the end of each e2e test.

2023-04-12 04:50 UTC, chaochn47 commented
Thanks @ahrtr !! I just realized it's concurrent stopping the members of cluster. My memory is sequential so I traced back why it is changed. 

https://github.com/etcd-io/etcd/pull/15242 is the culprit and confirmed by the following diagram. 
<img width="1836" alt="image" src="https://user-images.githubusercontent.com/54131596/231352587-bd113210-a93e-42c7-8a75-1f2437365e8f.png">

I would suggest we make concurrently stopping behavior opted-in by robustness test only but by default sequentially stopping each member process. WDYT? @ahrtr @fuweid @serathius

2023-04-12 05:15 UTC, ahrtr commented
> I would suggest we make concurrently stopping behavior opted-in by robustness test only but by default sequentially stopping each member process. WDYT? @ahrtr @fuweid @serathius

Firstly please change it to sequentially stopping and double confirm whether we can reduce the e2e overall duration. I see you already did it, thx.

Even we stop each member sequentially, but we did not remove each member from the cluster (we just stop the process); so when stopping the last member, it will still try to transfer the leadership, because there [still has multiple voting members](https://github.com/etcd-io/etcd/blob/6519a15db4c889601b713dac575379790d7fb691/server/etcdserver/server.go#L1217-L1224). Based on your input, it seems that sequentially stopping doesn't have such performance reduce. It conflicts with my understanding. I do not get enough time to dig into it. Please try to get this sorted out. thx

2023-04-12 05:20 UTC, ahrtr commented
I just did a quick verification, and confirmed that sequentially stopping doesn't have such performance issue. Please help me sort out the above confusion. thx 

```
$ go test -v -run "^TestMemberAdd/NotLearner/DisableStrictReconfigCheck/NoWaitForQuorum/PeerTLS$" --tags e2e
=== RUN   TestMemberAdd
    before.go:36: Changing working directory to: /var/folders/n9/qhsds19d75x16c351t6tzhfc0000gp/T/TestMemberAdd2848703705/001
=== RUN   TestMemberAdd/NotLearner/DisableStrictReconfigCheck/NoWaitForQuorum/PeerTLS
    logger.go:130: 2023-04-12T13:19:17.487+0800	INFO	starting server...	{"name": "TestMemberAddNotLearnerDisableStrictReconfigCheckNoWaitForQuorumPeerTLS-test-2"}
    logger.go:130: 2023-04-12T13:19:17.487+0800	INFO	starting server...	{"name": "TestMemberAddNotLearnerDisableStrictReconfigCheckNoWaitForQuorumPeerTLS-test-1"}
    logger.go:130: 2023-04-12T13:19:17.487+0800	INFO	starting server...	{"name": "TestMemberAddNotLearnerDisableStrictReconfigCheckNoWaitForQuorumPeerTLS-test-0"}
    logger.go:130: 2023-04-12T13:19:17.488+0800	INFO	spawning process	{"args": ["/Users/wachao/go/src/github.com/ahrtr/etcd/bin/etcd", "--name", "TestMemberAddNotLearnerDisableStrictReconfigCheckNoWaitForQuorumPeerTLS-test-2", "--listen-client-urls", "http://localhost:20010", "--advertise-client-urls", "http://localhost:20010", "--listen-peer-urls", "https://localhost:20011", "--initial-advertise-peer-urls", "https://localhost:20011", "--initial-cluster-token", "new", "--data-dir", "/var/folders/n9/qhsds19d75x16c351t6tzhfc0000gp/T/TestMemberAddNotLearnerDisableStrictReconfigCheckNoWaitForQuorumPeerTLS3515497785/003", "--snapshot-count", "10000", "--strict-reconfig-check=false", "--peer-cert-file", "/Users/wachao/go/src/github.com/ahrtr/etcd/tests/fixtures/server.crt", "--peer-key-file", "/Users/wachao/go/src/github.com/ahrtr/etcd/tests/fixtures/server.key.insecure", "--peer-trusted-ca-file", "/Users/wachao/go/src/github.com/ahrtr/etcd/tests/fixtures/ca.crt", "--initial-cluster", "TestMemberAddNotLearnerDisableStrictReconfigCheckNoWaitForQuorumPeerTLS-test-0=https://localhost:20001,TestMemberAddNotLearnerDisableStrictReconfigCheckNoWaitForQuorumPeerTLS-test-1=https://localhost:20006,TestMemberAddNotLearnerDisableStrictReconfigCheckNoWaitForQuorumPeerTLS-test-2=https://localhost:20011", "--initial-cluster-state", "new"], "working-dir": "/private/var/folders/n9/qhsds19d75x16c351t6tzhfc0000gp/T/TestMemberAdd2848703705/001", "name": "TestMemberAddNotLearnerDisableStrictReconfigCheckNoWaitForQuorumPeerTLS-test-2", "environment-variables": ["PATH=/Users/wachao/software/go/bin:/Users/wachao/software/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/wachao/software/go/bin:/Users/wachao/go/gopath/bin:/Users/wachao/software/umlet:/Users/wachao/software/jdk/Contents/Home/bin:/Users/wachao/software:/Users/wachao/software/etcd:/Users/wachao/software/goreman:/Users/wachao/onedrive/vmware/tkgi/utils:/Users/wachao/Library/Python/3.9/bin:/Users/wachao/software/protoc/bin:/Users/wachao/software/jmeter/bin:/Users/wachao/software/golangci:/Users/wachao/onedrive/open_source/etcd/utils:/Users/wachao/software:/Users/wachao/software/trivy", "ETCD_UNSUPPORTED_ARCH=amd64", "ETCD_VERIFY=all"]}
    logger.go:130: 2023-04-12T13:19:17.488+0800	INFO	spawning process	{"args": ["/Users/wachao/go/src/github.com/ahrtr/etcd/bin/etcd", "--name", "TestMemberAddNotLearnerDisableStrictReconfigCheckNoWaitForQuorumPeerTLS-test-0", "--listen-client-urls", "http://localhost:20000", "--advertise-client-urls", "http://localhost:20000", "--listen-peer-urls", "https://localhost:20001", "--initial-advertise-peer-urls", "https://localhost:20001", "--initial-cluster-token", "new", "--data-dir", "/var/folders/n9/qhsds19d75x16c351t6tzhfc0000gp/T/TestMemberAddNotLearnerDisableStrictReconfigCheckNoWaitForQuorumPeerTLS3515497785/001", "--snapshot-count", "10000", "--strict-reconfig-check=false", "--peer-cert-file", "/Users/wachao/go/src/github.com/ahrtr/etcd/tests/fixtures/server.crt", "--peer-key-file", "/Users/wachao/go/src/github.com/ahrtr/etcd/tests/fixtures/server.key.insecure", "--peer-trusted-ca-file", "/Users/wachao/go/src/github.com/ahrtr/etcd/tests/fixtures/ca.crt", "--initial-cluster", "TestMemberAddNotLearnerDisableStrictReconfigCheckNoWaitForQuorumPeerTLS-test-0=https://localhost:20001,TestMemberAddNotLearnerDisableStrictReconfigCheckNoWaitForQuorumPeerTLS-test-1=https://localhost:20006,TestMemberAddNotLearnerDisableStrictReconfigCheckNoWaitForQuorumPeerTLS-test-2=https://localhost:20011", "--initial-cluster-state", "new"], "working-dir": "/private/var/folders/n9/qhsds19d75x16c351t6tzhfc0000gp/T/TestMemberAdd2848703705/001", "name": "TestMemberAddNotLearnerDisableStrictReconfigCheckNoWaitForQuorumPeerTLS-test-0", "environment-variables": ["PATH=/Users/wachao/software/go/bin:/Users/wachao/software/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/wachao/software/go/bin:/Users/wachao/go/gopath/bin:/Users/wachao/software/umlet:/Users/wachao/software/jdk/Contents/Home/bin:/Users/wachao/software:/Users/wachao/software/etcd:/Users/wachao/software/goreman:/Users/wachao/onedrive/vmware/tkgi/utils:/Users/wachao/Library/Python/3.9/bin:/Users/wachao/software/protoc/bin:/Users/wachao/software/jmeter/bin:/Users/wachao/software/golangci:/Users/wachao/onedrive/open_source/etcd/utils:/Users/wachao/software:/Users/wachao/software/trivy", "ETCD_UNSUPPORTED_ARCH=amd64", "ETCD_VERIFY=all"]}
    logger.go:130: 2023-04-12T13:19:17.488+0800	INFO	spawning process	{"args": ["/Users/wachao/go/src/github.com/ahrtr/etcd/bin/etcd", "--name", "TestMemberAddNotLearnerDisableStrictReconfigCheckNoWaitForQuorumPeerTLS-test-1", "--listen-client-urls", "http://localhost:20005", "--advertise-client-urls", "http://localhost:20005", "--listen-peer-urls", "https://localhost:20006", "--initial-advertise-peer-urls", "https://localhost:20006", "--initial-cluster-token", "new", "--data-dir", "/var/folders/n9/qhsds19d75x16c351t6tzhfc0000gp/T/TestMemberAddNotLearnerDisableStrictReconfigCheckNoWaitForQuorumPeerTLS3515497785/002", "--snapshot-count", "10000", "--strict-reconfig-check=false", "--peer-cert-file", "/Users/wachao/go/src/github.com/ahrtr/etcd/tests/fixtures/server.crt", "--peer-key-file", "/Users/wachao/go/src/github.com/ahrtr/etcd/tests/fixtures/server.key.insecure", "--peer-trusted-ca-file", "/Users/wachao/go/src/github.com/ahrtr/etcd/tests/fixtures/ca.crt", "--initial-cluster", "TestMemberAddNotLearnerDisableStrictReconfigCheckNoWaitForQuorumPeerTLS-test-0=https://localhost:20001,TestMemberAddNotLearnerDisableStrictReconfigCheckNoWaitForQuorumPeerTLS-test-1=https://localhost:20006,TestMemberAddNotLearnerDisableStrictReconfigCheckNoWaitForQuorumPeerTLS-test-2=https://localhost:20011", "--initial-cluster-state", "new"], "working-dir": "/private/var/folders/n9/qhsds19d75x16c351t6tzhfc0000gp/T/TestMemberAdd2848703705/001", "name": "TestMemberAddNotLearnerDisableStrictReconfigCheckNoWaitForQuorumPeerTLS-test-1", "environment-variables": ["PATH=/Users/wachao/software/go/bin:/Users/wachao/software/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/wachao/software/go/bin:/Users/wachao/go/gopath/bin:/Users/wachao/software/umlet:/Users/wachao/software/jdk/Contents/Home/bin:/Users/wachao/software:/Users/wachao/software/etcd:/Users/wachao/software/goreman:/Users/wachao/onedrive/vmware/tkgi/utils:/Users/wachao/Library/Python/3.9/bin:/Users/wachao/software/protoc/bin:/Users/wachao/software/jmeter/bin:/Users/wachao/software/golangci:/Users/wachao/onedrive/open_source/etcd/utils:/Users/wachao/software:/Users/wachao/software/trivy", "ETCD_UNSUPPORTED_ARCH=amd64", "ETCD_VERIFY=all"]}
    logger.go:130: 2023-04-12T13:19:20.909+0800	INFO	started server.	{"name": "TestMemberAddNotLearnerDisableStrictReconfigCheckNoWaitForQuorumPeerTLS-test-2", "pid": 85623}
    logger.go:130: 2023-04-12T13:19:20.919+0800	INFO	started server.	{"name": "TestMemberAddNotLearnerDisableStrictReconfigCheckNoWaitForQuoru [...]

2023-04-12 05:27 UTC, chaochn47 commented
```
etcd (TestKVGetPeerAutoTLS-test-2) (2007481): {"level":"warn","ts":"2023-04-12T05:19:09.148099Z","caller":"etcdserver/server.go:1256","msg":"leadership transfer failed","local-member-id":"c61f33e98087dec2","error":"etcdserver: unhealthy cluster"}
```

TriggerLeadershipTransfer needs to pick a transferee that is longest connected. But during sequentially shutdown, the last member will find out its peers are no longer active. 

https://github.com/etcd-io/etcd/blob/6519a15db4c889601b713dac575379790d7fb691/server/etcdserver/server.go#L1226-L1229

That's my theory to explain why it takes short time to stop the cluster. I am confirming by adding logs...

2023-04-12 05:36 UTC, fuweid commented
> https://github.com/etcd-io/etcd/pull/15242 is the culprit and confirmed by the following diagram. You can see after the PR, e2e test was increased from 25m to 43m :(

It seems that my patch make it badly. Sorry about that :(. I am confirming it in my local as well. Thanks for pointing it out!

2023-04-12 06:04 UTC, chaochn47 commented
> etcdserver: request timed out, leader transfer took too long

Will try stop followers first and leave leader in the last step in the for loop.

2023-04-12 06:25 UTC, fuweid commented
Try it in my local.

```bash

2023-04-12 06:36 UTC, chaochn47 commented
I think the PR is good enough to reduce the common e2e test down from 29mins to 15mins. WDTY? 

> FYI. If the second stopped member is the leader, it also might lead to some delay (e.g. about 7s in this case) under sequentially stopping. I leave it to you to sort it out.

IMHO, the second stopped member should not even try to transfer the leadership if 1 member is not active and itself is trying to shutdown. Can I follow this up in a separate PR to follow single responsibility principle? @ahrtr 

> Last time I looked, leader will try to pass leadership before exiting. So we should have a tests for that behavior:
> 1. Test that in 3 member cluster leader will try to pass leadership when shut down
> 2. Test that in 3 member cluster leader will still shutdown if it cannot pass down leadership.
> 3. Test that in 1 member cluster passing leader is skipped

Can I follow this up in a separate PR to follow single responsibility principle? @serathius 

Raised a issue https://github.com/etcd-io/etcd/issues/15702 to track above and assigned to me.

2023-04-12 06:42 UTC, ahrtr commented
> I think the PR is good enough to reduce the common e2e test down from 29mins to 15mins. WDTY?

OK. Please get all the confusion sorted out in a separate session/PR.

2023-04-12 06:43 UTC, fuweid approved these changes
LGTM

2023-04-12 06:45 UTC, ahrtr approved these changes
LGTM

Thanks.

2023-04-12 06:45 UTC, merged

2023-04-12 06:51 UTC, chaochn47 commented
Thanks @ahrtr. I will get back to the https://github.com/etcd-io/etcd/issues/15702 tomorrow morning.