*: use strings.Builder instead of bytes.Buffer
etcd-io/etcd pull request #15908
Opened 2023-05-16 04:31 UTC by cuishuang

strings.Builder uses *(*string)(unsafe.Pointer(&b.buf)) to save the application memory operation when converting to a string

Updates https://github.com/etcd-io/etcd/issues/15910

2023-05-16 09:18 UTC, lavacat requested changes

2023-05-16 09:18 UTC, lavacat commented on pkg/cobrautl/help.go
> -	x := new(bytes.Buffer)
nit: remove "bytes" from import

2023-05-16 09:25 UTC, lavacat commented
Thanks for submitting the PR. Please open an issue and link 
https://go-review.googlesource.com/c/go/+/102479
https://go-review.googlesource.com/c/go/+/96980
As proof that this is needed.

2023-05-17 07:46 UTC, lavacat requested changes
please make sure code is compiling: `make build`

2023-05-17 07:46 UTC, lavacat commented on server/etcdserver/api/membership/cluster.go
> -	"go.etcd.io/raft/v3"
this should stay

2023-05-17 07:46 UTC, lavacat commented on server/etcdserver/api/rafthttp/snapshot_sender.go
> -	"go.etcd.io/raft/v3"
this file shouldn't change

2023-05-19 03:21 UTC, cuishuang commented
> @cuishuang please address failing "Static Analysis" check.
> 
> ```
> the following files are not sync with 'goimports'. run 'make fix'
> [430](https://github.com/etcd-io/etcd/actions/runs/5004332677/jobs/8966774215?pr=15908#step:6:431)
> /home/runner/work/etcd/etcd/server/etcdserver/api/rafthttp/snapshot_sender.go
> [431](https://github.com/etcd-io/etcd/actions/runs/5004332677/jobs/8966774215?pr=15908#step:6:432)
> There was a Failure in module server, aborting...
> ```

solved, thanks

2023-05-21 18:44 UTC, lavacat approved these changes

2023-05-21 18:47 UTC, lavacat commented
nit: please change commit msg to `*: use strings.Builder instead of bytes.Buffer`

2023-05-21 18:54 UTC, lavacat commented
I think this is ok to merge because it's a best practice. In terms of performance it might only matter in id.go and trace.go. This covers all [occurrences](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/etcd-io/etcd%24+bytes.Buffer+&patternType=standard&sm=1&groupBy=path) except for tests. cc @serathius @ahrtr

2023-05-21 22:09 UTC, ahrtr approved these changes
LGTM

Thanks

2023-05-22 01:36 UTC, cuishuang commented
> nit: please change commit msg to `*: use strings.Builder instead of bytes.Buffer`

Done. Thanks

2023-05-22 07:23 UTC, serathius approved these changes

2023-05-26 01:41 UTC, merged