feat: add etcd_server_range_duration_seconds metric
etcd-io/etcd pull request #16902
Opened 2023-11-09 16:02 UTC by RaviHari

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

2023-11-11 00:38 UTC, jmhbnz requested changes
Thanks for raising this @RaviHari - Could you please take a look at Integration or e2e tests for this new metric so we don't accidentally break it in future?

2023-11-14 03:38 UTC, lavacat requested changes

2023-11-14 03:38 UTC, lavacat commented on server/etcdserver/txn/txn.go
> +		RangeSecObserve(v3Version, op, success, time.Since(start))
I think it's better to remove "version" label, because it's always same value. The only benefit is that it follows `applySec` pattern.

2023-11-16 18:37 UTC, RaviHari commented
> Thanks for raising this @RaviHari - Could you please take a look at Integration or e2e tests for this new metric so we don't accidentally break it in future?

Hi @jmhbnz I looked at Integration and e2e tests it does not look like this change will break any of those tests.

2023-11-16 18:40 UTC, jmhbnz commented
> Hi @jmhbnz I looked at Integration and e2e tests it does not look like this change will break any of those tests.

Apologies I should have been more clear, I was asking if you could please add a test to ensure this metric does not get broken in future.

2023-12-12 18:49 UTC, lavacat commented
@RaviHari do you need help with figuring out where to add test?

2024-03-30 02:34 UTC, closed without merging