[3.5] Fix tx buffer inconsistency if there are duplicate keys in one tx.
etcd-io/etcd pull request #17239
Opened 2024-01-12 17:37 UTC by siyuanfoundation

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

Backport https://github.com/etcd-io/etcd/pull/17228 to 3.5

related to https://github.com/etcd-io/etcd/issues/17158

2024-01-12 18:30 UTC, siyuanfoundation commented
cc @ahrtr @serathius

2024-01-12 18:34 UTC, ahrtr approved these changes

2024-01-16 13:51 UTC, serathius requested changes
Blocking due to https://github.com/etcd-io/etcd/issues/17247

2024-11-10 09:17 UTC, ahrtr commented
The original PR https://github.com/etcd-io/etcd/pull/17228 has already been reverted.

2024-11-10 09:17 UTC, closed without merging