etcd 3.4: install shellcheck and report if not installed.
etcd-io/etcd pull request #18216
Opened 2024-06-23 19:26 UTC by thedtripp

Looking into https://github.com/etcd-io/etcd/issues/17472, it appears that shellcheck is not installed. I added some code to install it, though I'm not sure if this is the correct place to do this. 

At the very least, I think we should add an else block to inform that shellcheck isn't installed:

	if command -v shellcheck >/dev/null; then
		shellcheckResult=$(shellcheck -fgcc build test scripts/*.sh 2>&1 || true)
		if [ -n "${shellcheckResult}" ]; then
			echo -e "shellcheck checking failed:\\n${shellcheckResult}"
			exit 255
		fi
	else
		echo "Skipping shellcheck..."
	fi

2024-06-23 22:47 UTC, jmhbnz requested changes
Hey @thedtripp - Thanks for proposing this, agree `shellcheck` should be automatically installed if not already present.

We do already have this functionality in `main`, refer: https://github.com/etcd-io/etcd/pull/14872.

We should backport the approach from that pull request to `release-3.5` then `release-3.4` so all branches managed `shellcheck` the same way.

2024-06-24 14:55 UTC, idnandre commented
Hi @thedtripp @jmhbnz.
In "Tests / test (linux-amd64-fmt)" workflows there is still exists skipping revive message. Are we need to install revive also?

2024-06-25 00:48 UTC, thedtripp commented
> Hey @thedtripp - Thanks for proposing this, agree `shellcheck` should be automatically installed if not already present.
> 
> We do already have this functionality in `main`, refer: #14872.
> 
> We should backport the approach from that pull request to `release-3.5` then `release-3.4` so all branches managed `shellcheck` the same way.

Hey @jmhbnz. I submitted another PR for 3.5 here: https://github.com/etcd-io/etcd/pull/18229
If it looks good, I will repeat for 3.4. Thanks.

2024-06-25 00:49 UTC, thedtripp commented
> Hi @thedtripp @jmhbnz. In "Tests / test (linux-amd64-fmt)" workflows there is still exists skipping revive message. Are we need to install revive also?

Hey @idnandre,
Thanks for your review. I plan to address revive in a separate PR.

2024-06-29 00:21 UTC, jmhbnz commented
Closing in favor of #18248

2024-06-29 00:21 UTC, closed without merging