fix: use require instead of t.Fatal(err) in tests/integration package
etcd-io/etcd pull request #18820
Opened 2024-11-01 10:10 UTC by mmorel-35

#### Description

This uses testify instead of testing for t.Fatal calls

Related to #18972

2024-11-01 13:06 UTC, ahrtr commented
/ok-to-test

2024-11-03 20:03 UTC, ahrtr commented
Please try to breakdown the PR. We love small PR to make the review easy, although this PR is just mechanical changes.
Thanks

2024-12-02 13:26 UTC, ahrtr requested changes
Please breakdown this PR to smaller ones, thanks

2025-02-03 09:27 UTC, ahrtr commented
cc @fuweid @ivanvc @jmhbnz @serathius @siyuanfoundation

2025-02-03 14:33 UTC, fuweid approved these changes
LGTM

2025-02-03 14:45 UTC, merged